package eyre

object DefaultDllDefs {

	val gdi32 = arrayOf(
		"pldcGet", "AbortDoc", "DwmCreatedBitmapRemotingOutput", "AbortPath",
		"AddFontMemResourceEx", "AddFontResourceA", "AddFontResourceW", "AddFontResourceExA",
		"AddFontResourceExW", "AddFontResourceTracking", "AngleArc", "AnimatePalette",
		"AnyLinkedFonts", "Arc", "ArcTo", "BRUSHOBJ_hGetColorTransform",
		"BRUSHOBJ_pvAllocRbrush", "BRUSHOBJ_pvGetRbrush", "BRUSHOBJ_ulGetBrushColor", "BeginGdiRendering",
		"BeginPath", "BitBlt", "CLIPOBJ_bEnum", "CLIPOBJ_cEnumStart",
		"CLIPOBJ_ppoGetPath", "CancelDC", "CheckColorsInGamut", "ChoosePixelFormat",
		"Chord", "ClearBitmapAttributes", "ClearBrushAttributes", "CloseEnhMetaFile",
		"CloseFigure", "CloseMetaFile", "ColorCorrectPalette", "ColorMatchToTarget",
		"CombineRgn", "CombineTransform", "ConfigureOPMProtectedOutput", "CopyEnhMetaFileA",
		"CopyEnhMetaFileW", "CopyMetaFileA", "CopyMetaFileW", "CreateBitmap",
		"CreateBitmapFromDxSurface2", "CreateBitmapFromDxSurface", "CreateBitmapIndirect", "CreateBrushIndirect",
		"CreateColorSpaceA", "CreateColorSpaceW", "CreateCompatibleBitmap", "CreateCompatibleDC",
		"CreateDCA", "CreateDCW", "CreateDIBPatternBrush", "CreateDIBPatternBrushPt",
		"CreateDIBSection", "CreateDIBitmap", "CreateDPIScaledDIBSection", "CreateDiscardableBitmap",
		"CreateEllipticRgn", "CreateEllipticRgnIndirect", "CreateEnhMetaFileA", "CreateEnhMetaFileW",
		"CreateFontA", "CreateFontIndirectA", "CreateFontIndirectExA", "CreateFontIndirectExW",
		"CreateFontIndirectW", "CreateFontW", "CreateHalftonePalette", "CreateHatchBrush",
		"CreateICA", "CreateICW", "CreateMetaFileA", "CreateMetaFileW",
		"CreateOPMProtectedOutput", "CreateOPMProtectedOutputs", "CreatePalette", "CreatePatternBrush",
		"CreatePen", "CreatePenIndirect", "CreatePolyPolygonRgn", "CreatePolygonRgn",
		"CreateRectRgn", "CreateRectRgnIndirect",
		"CreateRoundRectRgn", "CreateScalableFontResourceA",
		"CreateScalableFontResourceW", "CreateScaledCompatibleBitmap",
		"CreateSessionMappedDIBSection", "CreateSolidBrush",
		"D3DKMTAbandonSwapChain", "D3DKMTAcquireKeyedMutex2",
		"D3DKMTAcquireKeyedMutex", "D3DKMTAcquireSwapChain",
		"D3DKMTAddSurfaceToSwapChain", "D3DKMTAdjustFullscreenGamma",
		"D3DKMTCacheHybridQueryValue", "D3DKMTChangeVideoMemoryReservation",
		"D3DKMTCheckExclusiveOwnership", "D3DKMTCheckMonitorPowerState",
		"D3DKMTCheckMultiPlaneOverlaySupport2", "D3DKMTCheckMultiPlaneOverlaySupport3",
		"D3DKMTCheckMultiPlaneOverlaySupport", "D3DKMTCheckOcclusion",
		"D3DKMTCheckSharedResourceAccess", "D3DKMTCheckVidPnExclusiveOwnership",
		"D3DKMTCloseAdapter", "D3DKMTConfigureSharedResource",
		"D3DKMTCreateAllocation2", "D3DKMTCreateAllocation",
		"D3DKMTCreateBundleObject", "D3DKMTCreateContext",
		"D3DKMTCreateContextVirtual", "D3DKMTCreateDCFromMemory",
		"D3DKMTCreateDevice", "D3DKMTCreateHwContext",
		"D3DKMTCreateHwQueue", "D3DKMTCreateKeyedMutex2",
		"D3DKMTCreateKeyedMutex", "D3DKMTCreateOutputDupl",
		"D3DKMTCreateOverlay", "D3DKMTCreatePagingQueue",
		"D3DKMTCreateProtectedSession", "D3DKMTCreateSwapChain",
		"D3DKMTCreateSynchronizationObject2", "D3DKMTCreateSynchronizationObject",
		"D3DKMTCreateTrackedWorkload", "D3DKMTDDisplayEnum",
		"D3DKMTDestroyAllocation2", "D3DKMTDestroyAllocation",
		"D3DKMTDestroyContext", "D3DKMTDestroyDCFromMemory",
		"D3DKMTDestroyDevice", "D3DKMTDestroyHwContext",
		"D3DKMTDestroyHwQueue", "D3DKMTDestroyKeyedMutex",
		"D3DKMTDestroyOutputDupl", "D3DKMTDestroyOverlay",
		"D3DKMTDestroyPagingQueue", "D3DKMTDestroyProtectedSession",
		"D3DKMTDestroySynchronizationObject", "D3DKMTDestroyTrackedWorkload",
		"D3DKMTDispMgrCreate", "D3DKMTDispMgrOperation",
		"D3DKMTDispMgrSourceOperation", "D3DKMTDispMgrTargetOperation",
		"D3DKMTDisplayPortOperation", "D3DKMTDuplicateHandle",
		"D3DKMTEnumAdapters2", "D3DKMTEnumAdapters3",
		"D3DKMTEnumAdapters", "D3DKMTEscape", "D3DKMTEvict", "D3DKMTExtractBundleObject",
		"D3DKMTFlipOverlay", "D3DKMTFlushHeapTransitions",
		"D3DKMTFreeGpuVirtualAddress", "D3DKMTGetAllocationPriority",
		"D3DKMTGetAvailableTrackedWorkloadIndex", "D3DKMTGetCachedHybridQueryValue",
		"D3DKMTGetContextInProcessSchedulingPriority", "D3DKMTGetContextSchedulingPriority",
		"D3DKMTGetDWMVerticalBlankEvent", "D3DKMTGetDeviceState",
		"D3DKMTGetDisplayModeList", "D3DKMTGetMemoryBudgetTarget",
		"D3DKMTGetMultiPlaneOverlayCaps", "D3DKMTGetMultisampleMethodList",
		"D3DKMTGetOverlayState", "D3DKMTGetPostCompositionCaps",
		"D3DKMTGetPresentHistory", "D3DKMTGetPresentQueueEvent",
		"D3DKMTGetProcessDeviceRemovalSupport", "D3DKMTGetProcessList",
		"D3DKMTGetProcessSchedulingPriorityBand", "D3DKMTGetProcessSchedulingPriorityClass",
		"D3DKMTGetResourcePresentPrivateDriverData", "D3DKMTGetRuntimeData",
		"D3DKMTGetScanLine", "D3DKMTGetSetSwapChainMetadata",
		"D3DKMTGetSharedPrimaryHandle", "D3DKMTGetSharedResourceAdapterLuid",
		"D3DKMTGetTrackedWorkloadStatistics", "D3DKMTGetYieldPercentage",
		"D3DKMTInvalidateActiveVidPn", "D3DKMTInvalidateCache",
		"D3DKMTLock2", "D3DKMTLock", "D3DKMTMakeResident", "D3DKMTMapGpuVirtualAddress",
		"D3DKMTMarkDeviceAsError", "D3DKMTNetDispGetNextChunkInfo",
		"D3DKMTNetDispQueryMiracastDisplayDeviceStatus", "D3DKMTNetDispQueryMiracastDisplayDeviceSupport",
		"D3DKMTNetDispStartMiracastDisplayDevice2", "D3DKMTNetDispStartMiracastDisplayDevice",
		"D3DKMTNetDispStartMiracastDisplayDeviceEx", "D3DKMTNetDispStopMiracastDisplayDevice",
		"D3DKMTOfferAllocations", "D3DKMTOpenAdapterFromDeviceName",
		"D3DKMTOpenAdapterFromGdiDisplayName", "D3DKMTOpenAdapterFromHdc",
		"D3DKMTOpenAdapterFromLuid", "D3DKMTOpenBundleObjectNtHandleFromName",
		"D3DKMTOpenKeyedMutex2", "D3DKMTOpenKeyedMutex",
		"D3DKMTOpenKeyedMutexFromNtHandle", "D3DKMTOpenNtHandleFromName",
		"D3DKMTOpenProtectedSessionFromNtHandle", "D3DKMTOpenResource2",
		"D3DKMTOpenResource", "D3DKMTOpenResourceFromNtHandle", "D3DKMTOpenSwapChain",
		"D3DKMTOpenSyncObjectFromNtHandle2",
		"D3DKMTOpenSyncObjectFromNtHandle", "D3DKMTOpenSyncObjectNtHandleFromName",
		"D3DKMTOpenSynchronizationObject", "D3DKMTOutputDuplGetFrameInfo",
		"D3DKMTOutputDuplGetMetaData", "D3DKMTOutputDuplGetPointerShapeData",
		"D3DKMTOutputDuplPresent", "D3DKMTOutputDuplPresentToHwQueue",
		"D3DKMTOutputDuplReleaseFrame", "D3DKMTPinDirectFlipResources",
		"D3DKMTPinResources", "D3DKMTPollDisplayChildren",
		"D3DKMTPresent", "D3DKMTPresentMultiPlaneOverlay2",
		"D3DKMTPresentMultiPlaneOverlay3", "D3DKMTPresentMultiPlaneOverlay",
		"D3DKMTPresentRedirected", "D3DKMTQueryAdapterInfo",
		"D3DKMTQueryAllocationResidency", "D3DKMTQueryClockCalibration",
		"D3DKMTQueryFSEBlock", "D3DKMTQueryProcessOfferInfo",
		"D3DKMTQueryProtectedSessionInfoFromNtHandle", "D3DKMTQueryProtectedSessionStatus",
		"D3DKMTQueryRemoteVidPnSourceFromGdiDisplayName", "D3DKMTQueryResourceInfo",
		"D3DKMTQueryResourceInfoFromNtHandle", "D3DKMTQueryStatistics",
		"D3DKMTQueryVidPnExclusiveOwnership", "D3DKMTQueryVideoMemoryInfo",
		"D3DKMTReclaimAllocations2", "D3DKMTReclaimAllocations",
		"D3DKMTRegisterTrimNotification", "D3DKMTRegisterVailProcess",
		"D3DKMTReleaseKeyedMutex2", "D3DKMTReleaseKeyedMutex",
		"D3DKMTReleaseProcessVidPnSourceOwners", "D3DKMTReleaseSwapChain",
		"D3DKMTRemoveSurfaceFromSwapChain", "D3DKMTRender",
		"D3DKMTReserveGpuVirtualAddress", "D3DKMTResetTrackedWorkloadStatistics",
		"D3DKMTSetAllocationPriority", "D3DKMTSetContextInProcessSchedulingPriority",
		"D3DKMTSetContextSchedulingPriority", "D3DKMTSetDisplayMode",
		"D3DKMTSetDisplayPrivateDriverFormat", "D3DKMTSetDodIndirectSwapchain",
		"D3DKMTSetFSEBlock", "D3DKMTSetGammaRamp",
		"D3DKMTSetHwProtectionTeardownRecovery", "D3DKMTSetMemoryBudgetTarget",
		"D3DKMTSetMonitorColorSpaceTransform", "D3DKMTSetProcessDeviceRemovalSupport",
		"D3DKMTSetProcessSchedulingPriorityBand", "D3DKMTSetProcessSchedulingPriorityClass",
		"D3DKMTSetQueuedLimit", "D3DKMTSetStablePowerState",
		"D3DKMTSetStereoEnabled", "D3DKMTSetSyncRefreshCountWaitTarget",
		"D3DKMTSetVidPnSourceHwProtection", "D3DKMTSetVidPnSourceOwner1",
		"D3DKMTSetVidPnSourceOwner2", "D3DKMTSetVidPnSourceOwner",
		"D3DKMTSetYieldPercentage", "D3DKMTShareObjects",
		"D3DKMTSharedPrimaryLockNotification", "D3DKMTSharedPrimaryUnLockNotification",
		"D3DKMTSignalSynchronizationObject2", "D3DKMTSignalSynchronizationObject",
		"D3DKMTSignalSynchronizationObjectFromCpu", "D3DKMTSignalSynchronizationObjectFromGpu2",
		"D3DKMTSignalSynchronizationObjectFromGpu", "D3DKMTSubmitCommand",
		"D3DKMTSubmitCommandToHwQueue", "D3DKMTSubmitPresentBltToHwQueue",
		"D3DKMTSubmitPresentToHwQueue", "D3DKMTSubmitSignalSyncObjectsToHwQueue",
		"D3DKMTSubmitWaitForSyncObjectsToHwQueue", "D3DKMTTrimProcessCommitment",
		"D3DKMTUnOrderedPresentSwapChain", "D3DKMTUnlock2", "D3DKMTUnlock", "D3DKMTUnpinDirectFlipResources",
		"D3DKMTUnpinResources", "D3DKMTUnregisterTrimNotification",
		"D3DKMTUpdateAllocationProperty", "D3DKMTUpdateGpuVirtualAddress",
		"D3DKMTUpdateOverlay", "D3DKMTUpdateTrackedWorkload",
		"D3DKMTVailConnect", "D3DKMTVailDisconnect",
		"D3DKMTVailPromoteCompositionSurface", "D3DKMTWaitForIdle",
		"D3DKMTWaitForSynchronizationObject2", "D3DKMTWaitForSynchronizationObject",
		"D3DKMTWaitForSynchronizationObjectFromCpu", "D3DKMTWaitForSynchronizationObjectFromGpu",
		"D3DKMTWaitForVerticalBlankEvent2", "D3DKMTWaitForVerticalBlankEvent",
		"DDCCIGetCapabilitiesString", "DDCCIGetCapabilitiesStringLength",
		"DDCCIGetTimingReport", "DDCCIGetVCPFeature",
		"DDCCISaveCurrentSettings", "DDCCISetVCPFeature", "DPtoLP", "DdCreateFullscreenSprite",
		"DdDestroyFullscreenSprite", "DdNotifyFullscreenSpriteUpdate",
		"DdQueryVisRgnUniqueness", "DeleteColorSpace",
		"DeleteDC", "DeleteEnhMetaFile", "DeleteMetaFile", "DeleteObject",
		"DescribePixelFormat", "DestroyOPMProtectedOutput",
		"DestroyPhysicalMonitorInternal", "DeviceCapabilitiesEx",
		"DeviceCapabilitiesExA", "DeviceCapabilitiesExW", "DrawEscape", "Ellipse",
		"EnableEUDC", "EndDoc", "EndFormPage", "EndGdiRendering",
		"EndPage", "EndPath", "EngAcquireSemaphore", "EngAlphaBlend",
		"EngAssociateSurface", "EngBitBlt", "EngCheckAbort", "EngComputeGlyphSet",
		"EngCopyBits", "EngCreateBitmap", "EngCreateClip", "EngCreateDeviceBitmap",
		"EngCreateDeviceSurface", "EngCreatePalette", "EngCreateSemaphore", "EngDeleteClip",
		"EngDeletePalette", "EngDeletePath", "EngDeleteSemaphore", "EngDeleteSurface",
		"EngEraseSurface", "EngFillPath", "EngFindResource", "EngFreeModule",
		"EngGetCurrentCodePage", "EngGetDriverName", "EngGetPrinterDataFileName", "EngGradientFill",
		"EngLineTo", "EngLoadModule", "EngLockSurface", "EngMarkBandingSurface",
		"EngMultiByteToUnicodeN", "EngMultiByteToWideChar", "EngPaint", "EngPlgBlt",
		"EngQueryEMFInfo", "EngQueryLocalTime", "EngReleaseSemaphore", "EngStretchBlt",
		"EngStretchBltROP", "EngStrokeAndFillPath", "EngStrokePath", "EngTextOut",
		"EngTransparentBlt", "EngUnicodeToMultiByteN", "EngUnlockSurface", "EngWideCharToMultiByte",
		"EnumEnhMetaFile", "EnumFontFamiliesA", "EnumFontFamiliesExA", "EnumFontFamiliesExW",
		"EnumFontFamiliesW", "EnumFontsA", "EnumFontsW", "EnumICMProfilesA",
		"EnumICMProfilesW", "EnumMetaFile", "EnumObjects", "EqualRgn",
		"Escape", "EudcLoadLinkW", "EudcUnloadLinkW", "ExcludeClipRect",
		"ExtCreatePen", "ExtCreateRegion", "ExtEscape", "ExtFloodFill",
		"ExtSelectClipRgn", "ExtTextOutA", "ExtTextOutW", "FONTOBJ_cGetAllGlyphHandles",
		"FONTOBJ_cGetGlyphs", "FONTOBJ_pQueryGlyphAttrs", "FONTOBJ_pfdg", "FONTOBJ_pifi",
		"FONTOBJ_pvTrueTypeFontFile", "FONTOBJ_pxoGetXform", "FONTOBJ_vGetInfo", "FillPath",
		"FillRgn", "FixBrushOrgEx", "FlattenPath", "FloodFill",
		"FontIsLinked", "FrameRgn", "Gdi32DllInitialize", "GdiAddFontResourceW",
		"GdiAddGlsBounds", "GdiAddGlsRecord", "GdiAddInitialFonts", "GdiAlphaBlend",
		"GdiArtificialDecrementDriver", "GdiCleanCacheDC", "GdiComment", "GdiConsoleTextOut",
		"GdiConvertAndCheckDC", "GdiConvertBitmap", "GdiConvertBitmapV5", "GdiConvertBrush",
		"GdiConvertDC", "GdiConvertEnhMetaFile", "GdiConvertFont", "GdiConvertMetaFilePict",
		"GdiConvertPalette", "GdiConvertRegion", "GdiConvertToDevmodeW", "GdiCreateLocalEnhMetaFile",
		"GdiCreateLocalMetaFilePict", "GdiCurrentProcessSplWow64", "GdiDeleteLocalDC", "GdiDeleteSpoolFileHandle",
		"GdiDescribePixelFormat", "GdiDllInitialize", "GdiDrawStream", "GdiEndDocEMF",
		"GdiEndPageEMF", "GdiEntry13", "GdiFlush", "GdiFullscreenControl",
		"GdiGetBatchLimit", "GdiGetBitmapBitsSize", "GdiGetCharDimensions", "GdiGetCodePage",
		"GdiGetDC", "GdiGetDevmodeForPage", "GdiGetEntry", "GdiGetLocalBrush",
		"GdiGetLocalDC", "GdiGetLocalFont", "GdiGetPageCount", "GdiGetPageHandle",
		"GdiGetSpoolFileHandle", "GdiGetSpoolMessage", "GdiGetVariationStoreDelta", "GdiGradientFill",
		"GdiInitSpool", "GdiInitializeLanguagePack", "GdiIsMetaFileDC", "GdiIsMetaPrintDC",
		"GdiIsPlayMetafileDC", "GdiIsScreenDC", "GdiIsTrackingEnabled", "GdiIsUMPDSandboxingEnabled",
		"GdiLoadType1Fonts", "GdiPlayDCScript", "GdiPlayEMF", "GdiPlayJournal",
		"GdiPlayPageEMF", "GdiPlayPrivatePageEMF", "GdiPlayScript", "GdiPrinterThunk",
		"GdiProcessSetup", "GdiQueryFonts", "GdiQueryTable", "GdiRealizationInfo",
		"GdiReleaseDC", "GdiReleaseLocalDC", "GdiResetDCEMF", "GdiSetAttrs",
		"GdiSetBatchLimit", "GdiSetLastError", "GdiSetPixelFormat", "GdiSetServerAttr",
		"GdiStartDocEMF", "GdiStartPageEMF", "GdiSupportsFontChangeEvent", "GdiSwapBuffers",
		"GdiTrackHCreate", "GdiTrackHDelete", "GdiTransparentBlt", "GdiValidateHandle",
		"GetArcDirection", "GetAspectRatioFilterEx", "GetBitmapAttributes", "GetBitmapBits",
		"GetBitmapDimensionEx", "GetBitmapDpiScaleValue", "GetBkColor", "GetBkMode",
		"GetBoundsRect", "GetBrushAttributes", "GetBrushOrgEx", "GetCOPPCompatibleOPMInformation",
		"GetCertificate", "GetCertificateByHandle", "GetCertificateSize", "GetCertificateSizeByHandle",
		"GetCharABCWidthsA", "GetCharABCWidthsFloatA", "GetCharABCWidthsFloatI", "GetCharABCWidthsFloatW",
		"GetCharABCWidthsI", "GetCharABCWidthsW", "GetCharWidth32A", "GetCharWidth32W",
		"GetCharWidthA", "GetCharWidthFloatA", "GetCharWidthFloatW", "GetCharWidthI",
		"GetCharWidthInfo", "GetCharWidthW", "GetCharacterPlacementA", "GetCharacterPlacementW",
		"GetClipBox", "GetClipRgn", "GetColorAdjustment", "GetColorSpace",
		"GetCurrentDpiInfo", "GetCurrentObject", "GetCurrentPositionEx", "GetDCBrushColor",
		"GetDCDpiScaleValue", "GetDCOrgEx", "GetDCPenColor", "GetDIBColorTable",
		"GetDIBits", "GetDeviceCaps", "GetDeviceGammaRamp", "GetETM",
		"GetEUDCTimeStamp", "GetEUDCTimeStampExW", "GetEnhMetaFileA", "GetEnhMetaFileBits",
		"GetEnhMetaFileDescriptionA", "GetEnhMetaFileDescriptionW",
		"GetEnhMetaFileHeader", "GetEnhMetaFilePaletteEntries",
		"GetEnhMetaFilePixelFormat", "GetEnhMetaFileW", "GetFontAssocStatus", "GetFontData",
		"GetFontFileData", "GetFontFileInfo", "GetFontLanguageInfo", "GetFontRealizationInfo",
		"GetFontResourceInfo", "GetFontResourceInfoW", "GetFontUnicodeRanges", "GetGlyphIndicesA",
		"GetGlyphIndicesW", "GetGlyphOutline", "GetGlyphOutlineA", "GetGlyphOutlineW",
		"GetGlyphOutlineWow", "GetGraphicsMode", "GetHFONT", "GetICMProfileA",
		"GetICMProfileW", "GetKerningPairs", "GetKerningPairsA", "GetKerningPairsW",
		"GetLayout", "GetLogColorSpaceA", "GetLogColorSpaceW", "GetMapMode",
		"GetMetaFileA", "GetMetaFileBitsEx", "GetMetaFileW", "GetMetaRgn",
		"GetMiterLimit", "GetNearestColor", "GetNearestPaletteIndex", "GetNumberOfPhysicalMonitors",
		"GetOPMInformation", "GetOPMRandomNumber", "GetObjectA", "GetObjectType",
		"GetObjectW", "GetOutlineTextMetricsA", "GetOutlineTextMetricsW", "GetPaletteEntries",
		"GetPath", "GetPhysicalMonitorDescription", "GetPhysicalMonitors", "GetPixel",
		"GetPixelFormat", "GetPolyFillMode", "GetProcessSessionFonts", "GetROP2",
		"GetRandomRgn", "GetRasterizerCaps", "GetRegionData", "GetRelAbs",
		"GetRgnBox", "GetStockObject", "GetStretchBltMode", "GetStringBitmapA",
		"GetStringBitmapW", "GetSuggestedOPMProtectedOutputArraySize",
		"GetSystemPaletteEntries", "GetSystemPaletteUse",
		"GetTextAlign", "GetTextCharacterExtra", "GetTextCharset", "GetTextCharsetInfo",
		"GetTextColor", "GetTextExtentExPointA", "GetTextExtentExPointI", "GetTextExtentExPointW",
		"GetTextExtentExPointWPri", "GetTextExtentPoint32A", "GetTextExtentPoint32W", "GetTextExtentPointA",
		"GetTextExtentPointI", "GetTextExtentPointW", "GetTextFaceA", "GetTextFaceAliasW",
		"GetTextFaceW", "GetTextMetricsA", "GetTextMetricsW", "GetTransform",
		"GetViewportExtEx", "GetViewportOrgEx", "GetWinMetaFileBits", "GetWindowExtEx",
		"GetWindowOrgEx", "GetWorldTransform", "HT_Get8BPPFormatPalette", "HT_Get8BPPMaskPalette",
		"InternalDeleteDC", "InternalDeleteObject", "IntersectClipRect", "InvertRgn",
		"IsValidEnhMetaRecord", "IsValidEnhMetaRecordOffExt", "LPtoDP", "LineDDA",
		"LineTo", "LpkDrawTextEx", "LpkExtTextOut", "LpkGetCharacterPlacement",
		"LpkGetEditControl", "LpkGetTextExtentExPoint", "LpkInitialize", "LpkPSMTextOut",
		"LpkPresent", "LpkTabbedTextOut", "LpkUseGDIWidthCache", "LpkpEditControlSize",
		"LpkpInitializeEditControl", "MaskBlt", "MirrorRgn", "ModerncoreCreateICW",
		"ModerncoreDeleteDC", "ModerncoreGdiInit", "ModifyWorldTransform", "MoveToEx",
		"NamedEscape", "OffsetClipRgn", "OffsetRgn", "OffsetViewportOrgEx",
		"OffsetWindowOrgEx", "PATHOBJ_bEnum", "PATHOBJ_bEnumClipLines", "PATHOBJ_vEnumStart",
		"PATHOBJ_vEnumStartClipLines", "PATHOBJ_vGetBounds", "PaintRgn", "PatBlt",
		"PathToRegion", "Pie", "PlayEnhMetaFile", "PlayEnhMetaFileRecord",
		"PlayMetaFile", "PlayMetaFileRecord", "PlgBlt", "PolyBezier",
		"PolyBezierTo", "PolyDraw", "PolyPatBlt", "PolyPolygon",
		"PolyPolyline", "PolyTextOutA", "PolyTextOutW", "Polygon",
		"Polyline", "PolylineTo", "PtInRegion", "PtVisible",
		"QueryFontAssocStatus", "RealizePalette", "RectInRegion", "RectVisible",
		"Rectangle", "RemoveFontMemResourceEx", "RemoveFontResourceA", "RemoveFontResourceExA",
		"RemoveFontResourceExW", "RemoveFontResourceTracking", "RemoveFontResourceW", "ResetDCA",
		"ResetDCW", "ResizePalette", "RestoreDC", "RoundRect",
		"STROBJ_bEnum", "STROBJ_bEnumPositionsOnly", "STROBJ_bGetAdvanceWidths", "STROBJ_dwGetCodePage",
		"STROBJ_vEnumStart", "SaveDC", "ScaleRgn", "ScaleValues",
		"ScaleViewportExtEx", "ScaleWindowExtEx", "ScriptApplyDigitSubstitution", "ScriptApplyLogicalWidth",
		"ScriptBreak", "ScriptCPtoX", "ScriptCacheGetHeight", "ScriptFreeCache",
		"ScriptGetCMap", "ScriptGetFontAlternateGlyphs", "ScriptGetFontFeatureTags", "ScriptGetFontLanguageTags",
		"ScriptGetFontProperties", "ScriptGetFontScriptTags", "ScriptGetGlyphABCWidth", "ScriptGetLogicalWidths",
		"ScriptGetProperties", "ScriptIsComplex", "ScriptItemize", "ScriptItemizeOpenType",
		"ScriptJustify", "ScriptLayout", "ScriptPlace", "ScriptPlaceOpenType",
		"ScriptPositionSingleGlyph", "ScriptRecordDigitSubstitution", "ScriptShape", "ScriptShapeOpenType",
		"ScriptStringAnalyse", "ScriptStringCPtoX", "ScriptStringFree", "ScriptStringGetLogicalWidths",
		"ScriptStringGetOrder", "ScriptStringOut", "ScriptStringValidate", "ScriptStringXtoCP",
		"ScriptString_pLogAttr", "ScriptString_pSize", "ScriptString_pcOutChars", "ScriptSubstituteSingleGlyph",
		"ScriptTextOut", "ScriptXtoCP", "SelectBrushLocal", "SelectClipPath",
		"SelectClipRgn", "SelectFontLocal", "SelectObject", "SelectPalette",
		"SetAbortProc", "SetArcDirection", "SetBitmapAttributes", "SetBitmapBits",
		"SetBitmapDimensionEx", "SetBkColor", "SetBkMode", "SetBoundsRect",
		"SetBrushAttributes", "SetBrushOrgEx", "SetColorAdjustment", "SetColorSpace",
		"SetDCBrushColor", "SetDCPenColor", "SetDIBColorTable", "SetDIBits",
		"SetDIBitsToDevice", "SetDeviceGammaRamp", "SetEnhMetaFileBits", "SetFontEnumeration",
		"SetGraphicsMode", "SetICMMode", "SetICMProfileA", "SetICMProfileW",
		"SetLayout", "SetLayoutWidth", "SetMagicColors", "SetMapMode",
		"SetMapperFlags", "SetMetaFileBitsEx", "SetMetaRgn", "SetMiterLimit",
		"SetOPMSigningKeyAndSequenceNumbers", "SetPaletteEntries", "SetPixel", "SetPixelFormat",
		"SetPixelV", "SetPolyFillMode", "SetROP2", "SetRectRgn",
		"SetRelAbs", "SetStretchBltMode", "SetSystemPaletteUse", "SetTextAlign",
		"SetTextCharacterExtra", "SetTextColor", "SetTextJustification", "SetViewportExtEx",
		"SetViewportOrgEx", "SetVirtualResolution", "SetWinMetaFileBits", "SetWindowExtEx",
		"SetWindowOrgEx", "SetWorldTransform", "StartDocA", "StartDocW",
		"StartFormPage", "StartPage", "StretchBlt", "StretchDIBits",
		"StrokeAndFillPath", "StrokePath", "SwapBuffers", "TextOutA",
		"TextOutW", "TranslateCharsetInfo", "UnloadNetworkFonts", "UnrealizeObject",
		"UpdateColors", "UpdateICMRegKeyA", "UpdateICMRegKeyW", "WidenPath",
		"gdiPlaySpoolStream",
	)

	val kernel32 = arrayOf(
		"BaseThreadInitThunk", "InterlockedPushListSList", "AcquireSRWLockExclusive", "AcquireSRWLockShared",
		"ActivateActCtx", "ActivateActCtxWorker", "AddAtomA", "AddAtomW",
		"AddConsoleAliasA", "AddConsoleAliasW", "AddDllDirectory", "AddIntegrityLabelToBoundaryDescriptor",
		"AddLocalAlternateComputerNameA", "AddLocalAlternateComputerNameW", "AddRefActCtx", "AddRefActCtxWorker",
		"AddResourceAttributeAce", "AddSIDToBoundaryDescriptor",
		"AddScopedPolicyIDAce", "AddSecureMemoryCacheCallback",
		"AddVectoredContinueHandler", "AddVectoredExceptionHandler", "AdjustCalendarDate", "AllocConsole",
		"AllocateUserPhysicalPages", "AllocateUserPhysicalPagesNuma",
		"AppPolicyGetClrCompat", "AppPolicyGetCreateFileAccess",
		"AAppPolicyGetLifecycleManagement", "AppPolicyGetMediaFoundationCodecLoading",
		"AppPolicyGetProcessTerminationMethod", "AppPolicyGetShowDeveloperDiagnostic",
		"AppPolicyGetThreadInitializationType", "AppPolicyGetWindowingModel",
		"AppXGetOSMaxVersionTested", "ApplicationRecoveryFinished",
		"ApplicationRecoveryInProgress", "AreFileApisANSI", "AssignProcessToJobObject", "AttachConsole",
		"BackupRead", "BackupSeek", "BackupWrite", "BaseAttachCompleteThunk",
		"BaseCheckAppcompatCache", "BaseCheckAppcompatCacheEx",
		"BaseCheckAppcompatCacheExWorker", "BaseCheckAppcompatCacheWorker",
		"BaseCheckElevation", "BaseCheckRunApp",
		"BaseCleanupAppcompatCacheSupport", "BaseDllReadWriteIniFile",
		"BaseDumpAppcompatCache", "BaseDumpAppcompatCacheWorker",
		"BaseElevationPostProcessing", "BaseFlushAppcompatCache",
		"BaseFlushAppcompatCacheWorker", "BaseFormatObjectAttributes",
		"BaseFormatTimeOut", "BaseFreeAppCompatDataForProcessWorker",
		"BaseGenerateAppCompatData", "BaseGetNamedObjectDirectory",
		"BaseInitAppcompatCacheSupport", "BaseInitAppcompatCacheSupportWorker",
		"BaseIsAppcompatInfrastructureDisabled", "BaseIsAppcompatInfrastructureDisabledWorker",
		"BaseIsDosApplication", "BaseQueryModuleData",
		"BaseReadAppCompatDataForProcessWorker", "BaseSetLastNTError",
		"BaseUpdateAppcompatCache", "BaseUpdateAppcompatCacheWorker",
		"BaseUpdateVDMEntry", "BaseVerifyUnicodeString",
		"BaseWriteErrorElevationRequiredEvent", "Basep8BitStringToDynamicUnicodeString",
		"BasepAllocateActivationContextActivationBlock", "BasepAnsiStringToDynamicUnicodeString",
		"BasepAppContainerEnvironmentExtension", "BasepAppXExtension",
		"BasepCheckAppCompat", "BasepCheckBadapp", "BasepCheckWebBladeHashes", "BasepCheckWinSaferRestrictions",
		"BasepConstructSxsCreateProcessMessage", "BasepCopyEncryption",
		"BasepFreeActivationContextActivationBlock", "BasepFreeAppCompatData",
		"BasepGetAppCompatData", "BasepGetComputerNameFromNtPath", "BasepGetExeArchType", "BasepInitAppCompatData",
		"BasepIsProcessAllowed", "BasepMapModuleHandle",
		"BasepNotifyLoadStringResource", "BasepPostSuccessAppXExtension",
		"BasepProcessInvalidImage", "BasepQueryAppCompat", "BasepQueryModuleChpeSettings", "BasepReleaseAppXContext",
		"BasepReleaseSxsCreateProcessUtilityStruct", "BasepReportFault", "BasepSetFileEncryptionCompression", "Beep",
		"BeginUpdateResourceA", "BeginUpdateResourceW", "BindIoCompletionCallback", "BuildCommDCBA",
		"BuildCommDCBAndTimeoutsA", "BuildCommDCBAndTimeoutsW", "BuildCommDCBW", "CallNamedPipeA",
		"CallNamedPipeW", "CallbackMayRunLong", "CancelDeviceWakeupRequest", "CancelIo",
		"CancelIoEx", "CancelSynchronousIo", "CancelThreadpoolIo", "CancelTimerQueueTimer",
		"CancelWaitableTimer", "CeipIsOptedIn", "ChangeTimerQueueTimer", "CheckAllowDecryptedRemoteDestinationPolicy",
		"CheckElevation", "CheckElevationEnabled", "CheckForReadOnlyResource", "CheckForReadOnlyResourceFilter",
		"CheckNameLegalDOS8Dot3A", "CheckNameLegalDOS8Dot3W", "CheckRemoteDebuggerPresent", "CheckTokenCapability",
		"CheckTokenMembershipEx", "ClearCommBreak", "ClearCommError", "CloseConsoleHandle",
		"CloseHandle", "ClosePackageInfo", "ClosePrivateNamespace", "CloseProfileUserMapping",
		"ClosePseudoConsole", "CloseState", "CloseThreadpool", "CloseThreadpoolCleanupGroup",
		"CloseThreadpoolCleanupGroupMembers", "CloseThreadpoolIo", "CloseThreadpoolTimer", "CloseThreadpoolWait",
		"CloseThreadpoolWork", "CmdBatNotification", "CommConfigDialogA", "CommConfigDialogW",
		"CompareCalendarDates", "CompareFileTime", "CompareStringA", "CompareStringEx",
		"CompareStringOrdinal", "CompareStringW", "ConnectNamedPipe", "ConsoleIMERoutine",
		"ConsoleMenuControl", "ContinueDebugEvent", "ConvertCalDateTimeToSystemTime", "ConvertDefaultLocale",
		"ConvertFiberToThread", "ConvertNLSDayOfWeekToWin32DayOfWeek",
		"ConvertSystemTimeToCalDateTime", "ConvertThreadToFiber",
		"ConvertThreadToFiberEx", "ConvertToGlobalHandle", "CopyContext", "CopyFile2",
		"CopyFileA", "CopyFileExA", "CopyFileExW", "CopyFileTransactedA",
		"CopyFileTransactedW", "CopyFileW", "CopyLZFile", "CreateActCtxA",
		"CreateActCtxW", "CreateActCtxWWorker", "CreateBoundaryDescriptorA", "CreateBoundaryDescriptorW",
		"CreateConsoleScreenBuffer", "CreateDirectoryA", "CreateDirectoryExA", "CreateDirectoryExW",
		"CreateDirectoryTransactedA", "CreateDirectoryTransactedW", "CreateDirectoryW", "CreateEnclave",
		"CreateEventA", "CreateEventExA", "CreateEventExW", "CreateEventW",
		"CreateFiber", "CreateFiberEx", "CreateFile2", "CreateFileA",
		"CreateFileMappingA", "CreateFileMappingFromApp", "CreateFileMappingNumaA", "CreateFileMappingNumaW",
		"CreateFileMappingW", "CreateFileTransactedA", "CreateFileTransactedW", "CreateFileW",
		"CreateHardLinkA", "CreateHardLinkTransactedA", "CreateHardLinkTransactedW", "CreateHardLinkW",
		"CreateIoCompletionPort", "CreateJobObjectA", "CreateJobObjectW", "CreateJobSet",
		"CreateMailslotA", "CreateMailslotW", "CreateMemoryResourceNotification", "CreateMutexA",
		"CreateMutexExA", "CreateMutexExW", "CreateMutexW", "CreateNamedPipeA",
		"CreateNamedPipeW", "CreatePipe", "CreatePrivateNamespaceA", "CreatePrivateNamespaceW",
		"CreateProcessA", "CreateProcessInternalA", "CreateProcessInternalW", "CreateProcessW",
		"CreatePseudoConsole", "CreateRemoteThread", "CreateRemoteThreadEx", "CreateSemaphoreA",
		"CreateSemaphoreExA", "CreateSemaphoreExW", "CreateSemaphoreW", "CreateSocketHandle",
		"CreateSymbolicLinkA", "CreateSymbolicLinkTransactedA",
		"CreateSymbolicLinkTransactedW", "CreateSymbolicLinkW",
		"CreateTapePartition", "CreateThread", "CreateThreadpool", "CreateThreadpoolCleanupGroup",
		"CreateThreadpoolIo", "CreateThreadpoolTimer", "CreateThreadpoolWait", "CreateThreadpoolWork",
		"CreateTimerQueue", "CreateTimerQueueTimer", "CreateToolhelp32Snapshot", "CreateVirtualBuffer",
		"CreateWaitableTimerA", "CreateWaitableTimerExA", "CreateWaitableTimerExW", "CreateWaitableTimerW",
		"CtrlRoutine", "DeactivateActCtx", "DeactivateActCtxWorker", "DebugActiveProcess",
		"DebugActiveProcessStop", "DebugBreak", "DebugBreakProcess", "DebugSetProcessKillOnExit",
		"DecodePointer", "DecodeSystemPointer", "DefineDosDeviceA", "DefineDosDeviceW",
		"DelayLoadFailureHook", "DeleteAtom", "DeleteBoundaryDescriptor", "DeleteCriticalSection",
		"DeleteFiber", "DeleteFileA", "DeleteFileTransactedA", "DeleteFileTransactedW",
		"DeleteFileW", "DeleteProcThreadAttributeList", "DeleteSynchronizationBarrier", "DeleteTimerQueue",
		"DeleteTimerQueueEx", "DeleteTimerQueueTimer", "DeleteVolumeMountPointA", "DeleteVolumeMountPointW",
		"DeviceIoControl", "DisableThreadLibraryCalls",
		"DisableThreadProfiling", "DisassociateCurrentThreadFromCallback",
		"DiscardVirtualMemory", "DisconnectNamedPipe", "DnsHostnameToComputerNameA", "DnsHostnameToComputerNameExW",
		"DnsHostnameToComputerNameW", "DosDateTimeToFileTime", "DosPathToSessionPathA", "DosPathToSessionPathW",
		"DuplicateConsoleHandle", "DuplicateEncryptionInfoFileExt", "DuplicateHandle", "EnableThreadProfiling",
		"EncodePointer", "EncodeSystemPointer", "EndUpdateResourceA", "EndUpdateResourceW",
		"EnterCriticalSection", "EnterSynchronizationBarrier", "EnumCalendarInfoA", "EnumCalendarInfoExA",
		"EnumCalendarInfoExEx", "EnumCalendarInfoExW", "EnumCalendarInfoW", "EnumDateFormatsA",
		"EnumDateFormatsExA", "EnumDateFormatsExEx", "EnumDateFormatsExW", "EnumDateFormatsW",
		"EnumLanguageGroupLocalesA", "EnumLanguageGroupLocalesW", "EnumResourceLanguagesA", "EnumResourceLanguagesExA",
		"EnumResourceLanguagesExW", "EnumResourceLanguagesW", "EnumResourceNamesA", "EnumResourceNamesExA",
		"EnumResourceNamesExW", "EnumResourceNamesW", "EnumResourceTypesA", "EnumResourceTypesExA",
		"EnumResourceTypesExW", "EnumResourceTypesW", "EnumSystemCodePagesA", "EnumSystemCodePagesW",
		"EnumSystemFirmwareTables", "EnumSystemGeoID", "EnumSystemGeoNames", "EnumSystemLanguageGroupsA",
		"EnumSystemLanguageGroupsW", "EnumSystemLocalesA", "EnumSystemLocalesEx", "EnumSystemLocalesW",
		"EnumTimeFormatsA", "EnumTimeFormatsEx", "EnumTimeFormatsW", "EnumUILanguagesA",
		"EnumUILanguagesW", "EnumerateLocalComputerNamesA", "EnumerateLocalComputerNamesW", "EraseTape",
		"EscapeCommFunction", "ExitProcess", "ExitThread", "ExitVDM",
		"ExpandEnvironmentStringsA", "ExpandEnvironmentStringsW",
		"ExpungeConsoleCommandHistoryA", "ExpungeConsoleCommandHistoryW",
		"ExtendVirtualBuffer", "FatalAppExitA", "FatalAppExitW", "FatalExit",
		"FileTimeToDosDateTime", "FileTimeToLocalFileTime", "FileTimeToSystemTime", "FillConsoleOutputAttribute",
		"FillConsoleOutputCharacterA", "FillConsoleOutputCharacterW",
		"FindActCtxSectionGuid", "FindActCtxSectionGuidWorker",
		"FindActCtxSectionStringA", "FindActCtxSectionStringW", "FindActCtxSectionStringWWorker", "FindAtomA",
		"FindAtomW", "FindClose", "FindCloseChangeNotification", "FindFirstChangeNotificationA",
		"FindFirstChangeNotificationW", "FindFirstFileA", "FindFirstFileExA", "FindFirstFileExW",
		"FindFirstFileNameTransactedW", "FindFirstFileNameW", "FindFirstFileTransactedA", "FindFirstFileTransactedW",
		"FindFirstFileW", "FindFirstStreamTransactedW", "FindFirstStreamW", "FindFirstVolumeA",
		"FindFirstVolumeMountPointA", "FindFirstVolumeMountPointW", "FindFirstVolumeW", "FindNLSString",
		"FindNLSStringEx", "FindNextChangeNotification", "FindNextFileA", "FindNextFileNameW",
		"FindNextFileW", "FindNextStreamW", "FindNextVolumeA", "FindNextVolumeMountPointA",
		"FindNextVolumeMountPointW", "FindNextVolumeW", "FindPackagesByPackageFamily", "FindResourceA",
		"FindResourceExA", "FindResourceExW", "FindResourceW", "FindStringOrdinal",
		"FindVolumeClose", "FindVolumeMountPointClose", "FlsAlloc", "FlsFree",
		"FlsGetValue", "FlsSetValue", "FlushConsoleInputBuffer", "FlushFileBuffers",
		"FlushInstructionCache", "FlushProcessWriteBuffers", "FlushViewOfFile", "FoldStringA",
		"FoldStringW", "FormatApplicationUserModelId", "FormatMessageA", "FormatMessageW",
		"FreeConsole", "FreeEnvironmentStringsA", "FreeEnvironmentStringsW", "FreeLibrary",
		"FreeLibraryAndExitThread", "FreeLibraryWhenCallbackReturns", "FreeMemoryJobObject", "FreeResource",
		"FreeUserPhysicalPages", "FreeVirtualBuffer", "GenerateConsoleCtrlEvent", "GetACP",
		"GetActiveProcessorCount", "GetActiveProcessorGroupCount",
		"GetAppContainerAce", "GetAppContainerNamedObjectPath",
		"GetApplicationRecoveryCallback", "GetApplicationRecoveryCallbackWorker",
		"GetApplicationRestartSettings", "GetApplicationRestartSettingsWorker",
		"GetApplicationUserModelId", "GetAtomNameA", "GetAtomNameW", "GetBinaryType",
		"GetBinaryTypeA", "GetBinaryTypeW", "GetCPFileNameFromRegistry", "GetCPInfo",
		"GetCPInfoExA", "GetCPInfoExW", "GetCachedSigningLevel", "GetCalendarDateFormat",
		"GetCalendarDateFormatEx", "GetCalendarDaysInMonth", "GetCalendarDifferenceInDays", "GetCalendarInfoA",
		"GetCalendarInfoEx", "GetCalendarInfoW", "GetCalendarMonthsInYear", "GetCalendarSupportedDateRange",
		"GetCalendarWeekNumber", "GetComPlusPackageInstallStatus", "GetCommConfig", "GetCommMask",
		"GetCommModemStatus", "GetCommProperties", "GetCommState", "GetCommTimeouts",
		"GetCommandLineA", "GetCommandLineW", "GetCompressedFileSizeA", "GetCompressedFileSizeTransactedA",
		"GetCompressedFileSizeTransactedW", "GetCompressedFileSizeW", "GetComputerNameA", "GetComputerNameExA",
		"GetComputerNameExW", "GetComputerNameW", "GetConsoleAliasA", "GetConsoleAliasExesA",
		"GetConsoleAliasExesLengthA", "GetConsoleAliasExesLengthW", "GetConsoleAliasExesW", "GetConsoleAliasW",
		"GetConsoleAliasesA", "GetConsoleAliasesLengthA", "GetConsoleAliasesLengthW", "GetConsoleAliasesW",
		"GetConsoleCP", "GetConsoleCharType", "GetConsoleCommandHistoryA", "GetConsoleCommandHistoryLengthA",
		"GetConsoleCommandHistoryLengthW", "GetConsoleCommandHistoryW", "GetConsoleCursorInfo", "GetConsoleCursorMode",
		"GetConsoleDisplayMode", "GetConsoleFontInfo", "GetConsoleFontSize", "GetConsoleHardwareState",
		"GetConsoleHistoryInfo", "GetConsoleInputExeNameA", "GetConsoleInputExeNameW", "GetConsoleInputWaitHandle",
		"GetConsoleKeyboardLayoutNameA", "GetConsoleKeyboardLayoutNameW", "GetConsoleMode", "GetConsoleNlsMode",
		"GetConsoleOriginalTitleA", "GetConsoleOriginalTitleW", "GetConsoleOutputCP", "GetConsoleProcessList",
		"GetConsoleScreenBufferInfo", "GetConsoleScreenBufferInfoEx", "GetConsoleSelectionInfo", "GetConsoleTitleA",
		"GetConsoleTitleW", "GetConsoleWindow", "GetCurrencyFormatA", "GetCurrencyFormatEx",
		"GetCurrencyFormatW", "GetCurrentActCtx", "GetCurrentActCtxWorker", "GetCurrentApplicationUserModelId",
		"GetCurrentConsoleFont", "GetCurrentConsoleFontEx", "GetCurrentDirectoryA", "GetCurrentDirectoryW",
		"GetCurrentPackageFamilyName", "GetCurrentPackageFullName", "GetCurrentPackageId", "GetCurrentPackageInfo",
		"GetCurrentPackagePath", "GetCurrentProcess", "GetCurrentProcessId", "GetCurrentProcessorNumber",
		"GetCurrentProcessorNumberEx", "GetCurrentThread", "GetCurrentThreadId", "GetCurrentThreadStackLimits",
		"GetDateFormatA", "GetDateFormatAWorker", "GetDateFormatEx", "GetDateFormatW",
		"GetDateFormatWWorker", "GetDefaultCommConfigA", "GetDefaultCommConfigW", "GetDevicePowerState",
		"GetDiskFreeSpaceA", "GetDiskFreeSpaceExA", "GetDiskFreeSpaceExW", "GetDiskFreeSpaceW",
		"GetDiskSpaceInformationA", "GetDiskSpaceInformationW", "GetDllDirectoryA", "GetDllDirectoryW",
		"GetDriveTypeA", "GetDriveTypeW", "GetDurationFormat", "GetDurationFormatEx",
		"GetDynamicTimeZoneInformation", "GetEnabledXStateFeatures",
		"GetEncryptedFileVersionExt", "GetEnvironmentStrings",
		"GetEnvironmentStringsA", "GetEnvironmentStringsW", "GetEnvironmentVariableA", "GetEnvironmentVariableW",
		"GetEraNameCountedString", "GetErrorMode", "GetExitCodeProcess", "GetExitCodeThread",
		"GetExpandedNameA", "GetExpandedNameW", "GetFileAttributesA", "GetFileAttributesExA",
		"GetFileAttributesExW", "GetFileAttributesTransactedA", "GetFileAttributesTransactedW", "GetFileAttributesW",
		"GetFileBandwidthReservation", "GetFileInformationByHandle", "GetFileInformationByHandleEx", "GetFileMUIInfo",
		"GetFileMUIPath", "GetFileSize", "GetFileSizeEx", "GetFileTime",
		"GetFileType", "GetFinalPathNameByHandleA", "GetFinalPathNameByHandleW", "GetFirmwareEnvironmentVariableA",
		"GetFirmwareEnvironmentVariableExA", "GetFirmwareEnvironmentVariableExW",
		"GetFirmwareEnvironmentVariableW", "GetFirmwareType",
		"GetFullPathNameA", "GetFullPathNameTransactedA", "GetFullPathNameTransactedW", "GetFullPathNameW",
		"GetGeoInfoA", "GetGeoInfoEx", "GetGeoInfoW", "GetHandleContext",
		"GetHandleInformation", "GetLargePageMinimum", "GetLargestConsoleWindowSize", "GetLastError",
		"GetLocalTime", "GetLocaleInfoA", "GetLocaleInfoEx", "GetLocaleInfoW",
		"GetLogicalDriveStringsA", "GetLogicalDriveStringsW", "GetLogicalDrives", "GetLogicalProcessorInformation",
		"GetLogicalProcessorInformationEx", "GetLongPathNameA",
		"GetLongPathNameTransactedA", "GetLongPathNameTransactedW",
		"GetLongPathNameW", "GetMailslotInfo", "GetMaximumProcessorCount", "GetMaximumProcessorGroupCount",
		"GetMemoryErrorHandlingCapabilities", "GetModuleFileNameA", "GetModuleFileNameW", "GetModuleHandleA",
		"GetModuleHandleExA", "GetModuleHandleExW", "GetModuleHandleW", "GetNLSVersion",
		"GetNLSVersionEx", "GetNamedPipeAttribute",
		"GetNamedPipeClientComputerNameA", "GetNamedPipeClientComputerNameW",
		"GetNamedPipeClientProcessId", "GetNamedPipeClientSessionId",
		"GetNamedPipeHandleStateA", "GetNamedPipeHandleStateW",
		"GetNamedPipeInfo", "GetNamedPipeServerProcessId", "GetNamedPipeServerSessionId", "GetNativeSystemInfo",
		"GetNextVDMCommand", "GetNumaAvailableMemoryNode", "GetNumaAvailableMemoryNodeEx", "GetNumaHighestNodeNumber",
		"GetNumaNodeNumberFromHandle", "GetNumaNodeProcessorMask",
		"GetNumaNodeProcessorMaskEx", "GetNumaProcessorNode",
		"GetNumaProcessorNodeEx", "GetNumaProximityNode", "GetNumaProximityNodeEx", "GetNumberFormatA",
		"GetNumberFormatEx", "GetNumberFormatW", "GetNumberOfConsoleFonts", "GetNumberOfConsoleInputEvents",
		"GetNumberOfConsoleMouseButtons", "GetOEMCP", "GetOverlappedResult", "GetOverlappedResultEx",
		"GetPackageApplicationIds", "GetPackageFamilyName", "GetPackageFullName", "GetPackageId",
		"GetPackageInfo", "GetPackagePath", "GetPackagePathByFullName", "GetPackagesByPackageFamily",
		"GetPhysicallyInstalledSystemMemory", "GetPriorityClass", "GetPrivateProfileIntA", "GetPrivateProfileIntW",
		"GetPrivateProfileSectionA", "GetPrivateProfileSectionNamesA",
		"GetPrivateProfileSectionNamesW", "GetPrivateProfileSectionW",
		"GetPrivateProfileStringA", "GetPrivateProfileStringW",
		"GetPrivateProfileStructA", "GetPrivateProfileStructW",
		"GetProcAddress", "GetProcessAffinityMask", "GetProcessDEPPolicy", "GetProcessDefaultCpuSets",
		"GetProcessGroupAffinity", "GetProcessHandleCount", "GetProcessHeap", "GetProcessHeaps",
		"GetProcessId", "GetProcessIdOfThread", "GetProcessInformation", "GetProcessIoCounters",
		"GetProcessMitigationPolicy", "GetProcessPreferredUILanguages",
		"GetProcessPriorityBoost", "GetProcessShutdownParameters",
		"GetProcessTimes", "GetProcessUserModeExceptionPolicy", "GetProcessVersion", "GetProcessWorkingSetSize",
		"GetProcessWorkingSetSizeEx", "GetProcessorSystemCycleTime", "GetProductInfo", "GetProductName",
		"GetProfileIntA", "GetProfileIntW", "GetProfileSectionA", "GetProfileSectionW",
		"GetProfileStringA", "GetProfileStringW", "GetQueuedCompletionStatus", "GetQueuedCompletionStatusEx",
		"GetShortPathNameA", "GetShortPathNameW", "GetStagedPackagePathByFullName", "GetStartupInfoA",
		"GetStartupInfoW", "GetStateFolder", "GetStdHandle", "GetStringScripts",
		"GetStringTypeA", "GetStringTypeExA", "GetStringTypeExW", "GetStringTypeW",
		"GetSystemAppDataKey", "GetSystemCpuSetInformation", "GetSystemDEPPolicy", "GetSystemDefaultLCID",
		"GetSystemDefaultLangID", "GetSystemDefaultLocaleName", "GetSystemDefaultUILanguage", "GetSystemDirectoryA",
		"GetSystemDirectoryW", "GetSystemFileCacheSize", "GetSystemFirmwareTable", "GetSystemInfo",
		"GetSystemPowerStatus", "GetSystemPreferredUILanguages", "GetSystemRegistryQuota", "GetSystemTime",
		"GetSystemTimeAdjustment", "GetSystemTimeAsFileTime", "GetSystemTimePreciseAsFileTime", "GetSystemTimes",
		"GetSystemWindowsDirectoryA", "GetSystemWindowsDirectoryW",
		"GetSystemWow64DirectoryA", "GetSystemWow64DirectoryW",
		"GetTapeParameters", "GetTapePosition", "GetTapeStatus", "GetTempFileNameA",
		"GetTempFileNameW", "GetTempPathA", "GetTempPathW", "GetThreadContext",
		"GetThreadDescription", "GetThreadErrorMode", "GetThreadGroupAffinity", "GetThreadIOPendingFlag",
		"GetThreadId", "GetThreadIdealProcessorEx", "GetThreadInformation", "GetThreadLocale",
		"GetThreadPreferredUILanguages", "GetThreadPriority", "GetThreadPriorityBoost", "GetThreadSelectedCpuSets",
		"GetThreadSelectorEntry", "GetThreadTimes", "GetThreadUILanguage", "GetTickCount64",
		"GetTickCount", "GetTimeFormatA", "GetTimeFormatAWorker", "GetTimeFormatEx",
		"GetTimeFormatW", "GetTimeFormatWWorker", "GetTimeZoneInformation", "GetTimeZoneInformationForYear",
		"GetUILanguageInfo", "GetUserDefaultGeoName", "GetUserDefaultLCID", "GetUserDefaultLangID",
		"GetUserDefaultLocaleName", "GetUserDefaultUILanguage", "GetUserGeoID", "GetUserPreferredUILanguages",
		"GetVDMCurrentDirectories", "GetVersion", "GetVersionExA", "GetVersionExW",
		"GetVolumeInformationA", "GetVolumeInformationByHandleW",
		"GetVolumeInformationW", "GetVolumeNameForVolumeMountPointA",
		"GetVolumeNameForVolumeMountPointW", "GetVolumePathNameA",
		"GetVolumePathNameW", "GetVolumePathNamesForVolumeNameA",
		"GetVolumePathNamesForVolumeNameW", "GetWindowsDirectoryA", "GetWindowsDirectoryW", "GetWriteWatch",
		"GetXStateFeaturesMask", "GlobalAddAtomA", "GlobalAddAtomExA", "GlobalAddAtomExW",
		"GlobalAddAtomW", "GlobalAlloc", "GlobalCompact", "GlobalDeleteAtom",
		"GlobalFindAtomA", "GlobalFindAtomW", "GlobalFix", "GlobalFlags",
		"GlobalFree", "GlobalGetAtomNameA", "GlobalGetAtomNameW", "GlobalHandle",
		"GlobalLock", "GlobalMemoryStatus", "GlobalMemoryStatusEx", "GlobalMemoryStatusVlm",
		"GlobalReAlloc", "GlobalSize", "GlobalUnWire", "GlobalUnfix",
		"GlobalUnlock", "GlobalWire", "Heap32First", "Heap32ListFirst",
		"Heap32ListNext", "Heap32Next", "HeapAlloc", "HeapCompact",
		"HeapCreate", "HeapCreateTagsW", "HeapDestroy", "HeapExtend",
		"HeapFree", "HeapLock", "HeapQueryInformation", "HeapQueryTagW",
		"HeapReAlloc", "HeapSetInformation", "HeapSize", "HeapSummary",
		"HeapUnlock", "HeapUsage", "HeapValidate", "HeapWalk",
		"IdnToAscii", "IdnToNameprepUnicode", "IdnToUnicode", "InitAtomTable",
		"InitializeCriticalSection", "InitOnceBeginInitialize", "InitOnceComplete", "InitOnceExecuteOnce",
		"InitOnceInitialize", "InitializeConditionVariable", "InitializeContext2", "InitializeContext",
		"InitializeCriticalSectionAndSpinCount", "InitializeCriticalSectionEx",
		"InitializeEnclave", "InitializeProcThreadAttributeList",
		"InitializeSListHead", "InitializeSRWLock", "InitializeSynchronizationBarrier", "InstallELAMCertificateInfo",
		"InterlockedCompareExchange64", "InterlockedCompareExchange", "InterlockedDecrement", "InterlockedExchange",
		"InterlockedExchangeAdd", "InterlockedFlushSList", "InterlockedIncrement", "InterlockedPopEntrySList",
		"InterlockedPushEntrySList", "InterlockedPushListSListEx", "InvalidateConsoleDIBits", "IsBadCodePtr",
		"IsBadHugeReadPtr", "IsBadHugeWritePtr", "IsBadReadPtr", "IsBadStringPtrA",
		"IsBadStringPtrW", "IsBadWritePtr", "IsCalendarLeapDay", "IsCalendarLeapMonth",
		"IsCalendarLeapYear", "IsDBCSLeadByte", "IsDBCSLeadByteEx", "IsDebuggerPresent",
		"IsEnclaveTypeSupported", "IsNLSDefinedString", "IsNativeVhdBoot", "IsNormalizedString",
		"IsProcessCritical", "IsProcessInJob", "IsProcessorFeaturePresent", "IsSystemResumeAutomatic",
		"IsThreadAFiber", "IsThreadpoolTimerSet", "IsTimeZoneRedirectionEnabled", "IsValidCalDateTime",
		"IsValidCodePage", "IsValidLanguageGroup", "IsValidLocale", "IsValidLocaleName",
		"IsValidNLSVersion", "IsWow64GuestMachineSupported", "IsWow64Process2", "IsWow64Process",
		"K32EmptyWorkingSet", "K32EnumDeviceDrivers", "K32EnumPageFilesA", "K32EnumPageFilesW",
		"K32EnumProcessModules", "K32EnumProcessModulesEx", "K32EnumProcesses", "K32GetDeviceDriverBaseNameA",
		"K32GetDeviceDriverBaseNameW", "K32GetDeviceDriverFileNameA",
		"K32GetDeviceDriverFileNameW", "K32GetMappedFileNameA",
		"K32GetMappedFileNameW", "K32GetModuleBaseNameA", "K32GetModuleBaseNameW", "K32GetModuleFileNameExA",
		"K32GetModuleFileNameExW", "K32GetModuleInformation", "K32GetPerformanceInfo", "K32GetProcessImageFileNameA",
		"K32GetProcessImageFileNameW", "K32GetProcessMemoryInfo", "K32GetWsChanges", "K32GetWsChangesEx",
		"K32InitializeProcessForWsWatch", "K32QueryWorkingSet", "K32QueryWorkingSetEx", "LCIDToLocaleName",
		"LCMapStringA", "LCMapStringEx", "LCMapStringW", "LZClose",
		"LZCloseFile", "LZCopy", "LZCreateFileW", "LZDone",
		"LZInit", "LZOpenFileA", "LZOpenFileW", "LZRead",
		"LZSeek", "LZStart", "LeaveCriticalSection", "LeaveCriticalSectionWhenCallbackReturns",
		"LoadAppInitDlls", "LoadEnclaveData", "LoadLibraryA", "LoadLibraryExA",
		"LoadLibraryExW", "LoadLibraryW", "LoadModule", "LoadPackagedLibrary",
		"LoadResource", "LoadStringBaseExW", "LoadStringBaseW", "LocalAlloc",
		"LocalCompact", "LocalFileTimeToFileTime", "LocalFileTimeToLocalSystemTime", "LocalFlags",
		"LocalFree", "LocalHandle", "LocalLock", "LocalReAlloc",
		"LocalShrink", "LocalSize", "LocalSystemTimeToLocalFileTime", "LocalUnlock",
		"LocaleNameToLCID", "LocateXStateFeature", "LockFile", "LockFileEx",
		"LockResource", "MapUserPhysicalPages", "MapUserPhysicalPagesScatter", "MapViewOfFile",
		"MapViewOfFileEx", "MapViewOfFileExNuma", "MapViewOfFileVlm", "MapViewOfFileFromApp",
		"Module32First", "Module32FirstW", "Module32Next", "Module32NextW",
		"MoveFileA", "MoveFileExA", "MoveFileExW", "MoveFileTransactedA",
		"MoveFileTransactedW", "MoveFileW", "MoveFileWithProgressA", "MoveFileWithProgressW",
		"MulDiv", "MultiByteToWideChar", "NeedCurrentDirectoryForExePathA", "NeedCurrentDirectoryForExePathW",
		"NlsCheckPolicy", "NlsConvertIntegerToString", "NlsEventDataDescCreate", "NlsGetCacheUpdateCount",
		"NlsUpdateLocale", "NlsUpdateSystemLocale", "NlsWriteEtwEvent", "NormalizeString",
		"NotifyMountMgr", "NotifyUILanguageChange", "NtVdm64CreateProcessInternalW", "OOBEComplete",
		"OfferVirtualMemory", "OpenConsoleW", "OpenConsoleWStub", "OpenEventA",
		"OpenEventW", "OpenFile", "OpenFileById", "OpenFileMappingA",
		"OpenFileMappingW", "OpenJobObjectA", "OpenJobObjectW", "OpenMutexA",
		"OpenMutexW", "OpenPackageInfoByFullName", "OpenPrivateNamespaceA", "OpenPrivateNamespaceW",
		"OpenProcess", "OpenProfileUserMapping", "OpenSemaphoreA", "OpenSemaphoreW",
		"OpenState", "OpenStateExplicit", "OpenThread", "OpenWaitableTimerA",
		"OpenWaitableTimerW", "OutputDebugStringA", "OutputDebugStringW", "PackageFamilyNameFromFullName",
		"PackageFamilyNameFromId", "PackageFullNameFromId",
		"PackageIdFromFullName", "PackageNameAndPublisherIdFromFamilyName",
		"ParseApplicationUserModelId", "PeekConsoleInputA", "PeekConsoleInputW", "PeekNamedPipe",
		"PostQueuedCompletionStatus", "PowerClearRequest", "PowerCreateRequest", "PowerSetRequest",
		"PrefetchVirtualMemory", "PrepareTape", "PrivCopyFileExW", "PrivMoveFileIdentityW",
		"Process32First", "Process32FirstW", "Process32Next", "Process32NextW",
		"ProcessIdToSessionId", "PssCaptureSnapshot", "PssDuplicateSnapshot", "PssFreeSnapshot",
		"PssQuerySnapshot", "PssWalkMarkerCreate", "PssWalkMarkerFree", "PssWalkMarkerGetPosition",
		"PssWalkMarkerRewind", "PssWalkMarkerSeek", "PssWalkMarkerSeekToBeginning", "PssWalkMarkerSetPosition",
		"PssWalkMarkerTell", "PssWalkSnapshot", "PulseEvent", "PurgeComm",
		"QueryActCtxSettingsW", "QueryActCtxSettingsWWorker", "QueryActCtxW", "QueryActCtxWWorker",
		"QueryDepthSList", "QueryDosDeviceA", "QueryDosDeviceW", "QueryFullProcessImageNameA",
		"QueryFullProcessImageNameW", "QueryIdleProcessorCycleTime",
		"QueryIdleProcessorCycleTimeEx", "QueryInformationJobObject",
		"QueryIoRateControlInformationJobObject", "QueryMemoryResourceNotification",
		"QueryPerformanceCounter", "QueryPerformanceFrequency",
		"QueryProcessAffinityUpdateMode", "QueryProcessCycleTime", "QueryProtectedPolicy", "QueryThreadCycleTime",
		"QueryThreadProfiling", "QueryThreadpoolStackInformation", "QueryUnbiasedInterruptTime", "QueueUserAPC",
		"QueueUserWorkItem", "QueryWin31IniFilesMappedToRegistry", "QuirkGetData2Worker", "QuirkGetDataWorker",
		"QuirkIsEnabled2Worker", "QuirkIsEnabled3Worker",
		"QuirkIsEnabledForPackage2Worker", "QuirkIsEnabledForPackage3Worker",
		"QuirkIsEnabledForPackage4Worker", "QuirkIsEnabledForPackageWorker",
		"QuirkIsEnabledForProcessWorker", "QuirkIsEnabledWorker",
		"RaiseException", "RaiseFailFastException", "RaiseInvalid16BitExeError", "ReOpenFile",
		"ReclaimVirtualMemory", "ReadConsoleA", "ReadConsoleInputA", "ReadConsoleInputExA",
		"ReadConsoleInputExW", "ReadConsoleInputW", "ReadConsoleOutputA", "ReadConsoleOutputAttribute",
		"ReadConsoleOutputCharacterA", "ReadConsoleOutputCharacterW", "ReadConsoleOutputW", "ReadConsoleW",
		"ReadDirectoryChangesExW", "ReadDirectoryChangesW", "ReadFile", "ReadFileEx",
		"ReadFileScatter", "ReadFileVlm", "ReadProcessMemory", "ReadThreadProfilingData",
		"RegisterApplicationRecoveryCallback", "RegisterApplicationRestart",
		"RegisterBadMemoryNotification", "RegisterConsoleIME",
		"RegisterConsoleOS2", "RegisterConsoleVDM", "RegisterWaitForInputIdle", "RegisterWaitForSingleObject",
		"RegisterWaitForSingleObjectEx", "RegisterWaitUntilOOBECompleted",
		"RegisterWowBaseHandlers", "RegisterWowExec",
		"ReleaseActCtx", "ReleaseActCtxWorker", "ReleaseMutex", "ReleaseMutexWhenCallbackReturns",
		"ReleaseSRWLockExclusive", "ReleaseSRWLockShared", "ReleaseSemaphore", "ReleaseSemaphoreWhenCallbackReturns",
		"ResolveLocaleName", "RemoveDirectoryA", "RemoveDirectoryTransactedA", "RemoveDirectoryTransactedW",
		"RemoveDirectoryW", "RemoveDllDirectory",
		"RemoveLocalAlternateComputerNameA", "RemoveLocalAlternateComputerNameW",
		"RemoveSecureMemoryCacheCallback", "RemoveVectoredContinueHandler",
		"RemoveVectoredExceptionHandler", "ReplaceFile",
		"ReplaceFileA", "ReplaceFileW", "ReplacePartitionUnit", "RequestDeviceWakeup",
		"RequestWakeupLatency", "ResetEvent", "ResetWriteWatch", "ResizePseudoConsole",
		"ResolveDelayLoadedAPI", "ResolveDelayLoadsFromDll", "RestoreLastError", "ResumeThread",
		"RtlCaptureContext", "RtlCaptureStackBackTrace", "RtlFillMemory", "RtlMoveMemory",
		"RtlPcToFileHeader", "RtlUnwind", "RtlZeroMemory", "ScrollConsoleScreenBufferA",
		"ScrollConsoleScreenBufferW", "SearchPathA", "SearchPathW", "SetCachedSigningLevel",
		"SetCalendarInfoA", "SetCalendarInfoW", "SetClientTimeZoneInformation", "SetComPlusPackageInstallStatus",
		"SetCommBreak", "SetCommConfig", "SetCommMask", "SetCommState",
		"SetCommTimeouts", "SetComputerNameA", "SetComputerNameEx2W", "SetComputerNameExA",
		"SetComputerNameExW", "SetComputerNameW", "SetConsoleActiveScreenBuffer", "SetConsoleCP",
		"SetConsoleCommandHistoryMode", "SetConsoleCtrlHandler", "SetConsoleCursor", "SetConsoleCursorInfo",
		"SetConsoleCursorMode", "SetConsoleCursorPosition", "SetConsoleDisplayMode", "SetConsoleFont",
		"SetConsoleHardwareState", "SetConsoleHistoryInfo", "SetConsoleIcon", "SetConsoleInputExeNameA",
		"SetConsoleInputExeNameW", "SetConsoleKeyShortcuts", "SetConsoleLocalEUDC", "SetConsoleMaximumWindowSize",
		"SetConsoleMenuClose", "SetConsoleMode", "SetConsoleNlsMode", "SetConsoleNumberOfCommandsA",
		"SetConsoleNumberOfCommandsW", "SetConsoleOS2OemFormat", "SetConsoleOutputCP", "SetConsolePalette",
		"SetConsoleScreenBufferInfoEx", "SetConsoleScreenBufferSize", "SetConsoleTextAttribute", "SetConsoleTitleA",
		"SetConsoleTitleW", "SetConsoleWindowInfo", "SetCriticalSectionSpinCount", "SetCurrentConsoleFontEx",
		"SetCurrentDirectoryA", "SetCurrentDirectoryW", "SetDefaultCommConfigA", "SetDefaultCommConfigW",
		"SetDefaultDllDirectories", "SetDllDirectoryA", "SetDllDirectoryW", "SetDynamicTimeZoneInformation",
		"SetEndOfFile", "SetEnvironmentStringsA", "SetEnvironmentStringsW", "SetEnvironmentVariableA",
		"SetEnvironmentVariableW", "SetErrorMode", "SetEvent", "SetEventWhenCallbackReturns",
		"SetFileApisToANSI", "SetFileApisToOEM", "SetFileAttributesA", "SetFileAttributesTransactedA",
		"SetFileAttributesTransactedW", "SetFileAttributesW",
		"SetFileBandwidthReservation", "SetFileCompletionNotificationModes",
		"SetFileInformationByHandle", "SetFileIoOverlappedRange", "SetFilePointer", "SetFilePointerEx",
		"SetFileShortNameA", "SetFileShortNameW", "SetFileTime", "SetFileValidData",
		"SetFirmwareEnvironmentVariableA", "SetFirmwareEnvironmentVariableExA",
		"SetFirmwareEnvironmentVariableExW", "SetFirmwareEnvironmentVariableW",
		"SetHandleContext", "SetHandleCount", "SetHandleInformation", "SetInformationJobObject",
		"SetIoRateControlInformationJobObject", "SetLastConsoleEventActive",
		"SetLastError", "SetLocalPrimaryComputerNameA",
		"SetLocalPrimaryComputerNameW", "SetLocalTime", "SetLocaleInfoA", "SetLocaleInfoW",
		"SetMailslotInfo", "SetMessageWaitingIndicator", "SetNamedPipeAttribute", "SetNamedPipeHandleState",
		"SetPriorityClass", "SetProcessAffinityMask", "SetProcessAffinityUpdateMode", "SetProcessDEPPolicy",
		"SetProcessDefaultCpuSets", "SetProcessInformation",
		"SetProcessMitigationPolicy", "SetProcessPreferredUILanguages",
		"SetProcessPriorityBoost", "SetProcessShutdownParameters",
		"SetProcessUserModeExceptionPolicy", "SetProcessWorkingSetSize",
		"SetProcessWorkingSetSizeEx", "SetProtectedPolicy", "SetSearchPathMode", "SetStdHandle",
		"SetStdHandleEx", "SetSystemFileCacheSize", "SetSystemPowerState", "SetSystemTime",
		"SetSystemTimeAdjustment", "SetTapeParameters", "SetTapePosition", "SetTermsrvAppInstallMode",
		"SetThreadAffinityMask", "SetThreadContext", "SetThreadDescription", "SetThreadErrorMode",
		"SetThreadExecutionState", "SetThreadGroupAffinity",
		"SetThreadIdealProcessor", "SetThreadIdealProcessorEx",
		"SetThreadInformation", "SetThreadLocale",
		"SetThreadPreferredUILanguages", "SetThreadPriority",
		"SetThreadPriorityBoost", "SetThreadSelectedCpuSets",
		"SetThreadStackGuarantee", "SetThreadUILanguage",
		"SetThreadpoolStackInformation", "SetThreadpoolThreadMaximum",
		"SetThreadpoolThreadMinimum", "SetThreadpoolTimer",
		"SetThreadpoolTimerEx", "SetThreadpoolWait", "SetThreadpoolWaitEx", "SetTimeZoneInformation",
		"SetTimerQueueTimer", "SetUnhandledExceptionFilter", "SetUserGeoID", "SetUserGeoName",
		"SetVDMCurrentDirectories", "SetVolumeLabelA", "SetVolumeLabelW", "SetVolumeMountPointA",
		"SetVolumeMountPointW", "SetVolumeMountPointWStub", "SetWaitableTimer", "SetWaitableTimerEx",
		"SetXStateFeaturesMask", "SetupComm", "ShowConsoleCursor", "SignalObjectAndWait",
		"SizeofResource", "Sleep", "SleepConditionVariableCS", "SleepConditionVariableSRW",
		"SleepEx", "SortCloseHandle", "SortGetHandle", "StartThreadpoolIo",
		"SubmitThreadpoolWork", "SuspendThread", "SwitchToFiber", "SwitchToThread",
		"SystemTimeToFileTime", "SystemTimeToTzSpecificLocalTime",
		"SystemTimeToTzSpecificLocalTimeEx", "TerminateJobObject",
		"TerminateProcess", "TerminateThread", "TermsrvAppInstallMode", "TermsrvConvertSysRootToUserDir",
		"TermsrvCreateRegEntry", "TermsrvDeleteKey", "TermsrvDeleteValue", "TermsrvGetPreSetValue",
		"TermsrvGetWindowsDirectoryA", "TermsrvGetWindowsDirectoryW",
		"TermsrvOpenRegEntry", "TermsrvOpenUserClasses",
		"TermsrvRestoreKey", "TermsrvSetKeySecurity", "TermsrvSetValueKey", "TermsrvSyncUserIniFileExt",
		"Thread32First", "Thread32Next", "TlsAlloc", "TlsFree",
		"TlsGetValue", "TlsSetValue", "Toolhelp32ReadProcessMemory", "TransactNamedPipe",
		"TransmitCommChar", "TrimVirtualBuffer", "TryAcquireSRWLockExclusive", "TryAcquireSRWLockShared",
		"TryEnterCriticalSection", "TrySubmitThreadpoolCallback",
		"TzSpecificLocalTimeToSystemTime", "TzSpecificLocalTimeToSystemTimeEx",
		"UTRegister", "UTUnRegister", "UnhandledExceptionFilter", "UnlockFile",
		"UnlockFileEx", "UnmapViewOfFile", "UnmapViewOfFileVlm", "UnregisterApplicationRecoveryCallback",
		"UnregisterApplicationRestart", "UnregisterBadMemoryNotification",
		"UnregisterConsoleIME", "UnregisterWait",
		"UnregisterWaitEx", "UnregisterWaitUntilOOBECompleted",
		"UpdateCalendarDayOfWeek", "UpdateProcThreadAttribute",
		"UpdateResourceA", "UpdateResourceW", "VDMConsoleOperation", "VDMOperationStarted",
		"VerLanguageNameA", "VerLanguageNameW", "VerSetConditionMask", "VerifyConsoleIoHandle",
		"VerifyScripts", "VerifyVersionInfoA", "VerifyVersionInfoW", "VirtualAlloc",
		"VirtualAllocEx", "VirtualAllocExNuma", "VirtualAllocVlm", "VirtualBufferExceptionHandler",
		"VirtualFree", "VirtualFreeEx", "VirtualFreeVlm", "VirtualLock",
		"VirtualProtect", "VirtualProtectEx", "VirtualProtectVlm", "VirtualQuery",
		"VirtualQueryEx", "VirtualQueryVlm", "VirtualUnlock", "WTSGetActiveConsoleSessionId",
		"WaitCommEvent", "WaitForDebugEvent", "WaitForMultipleObjects", "WaitForMultipleObjectsEx",
		"WaitForSingleObject", "WaitForSingleObjectEx",
		"WaitForThreadpoolIoCallbacks", "WaitForThreadpoolTimerCallbacks",
		"WaitForThreadpoolWaitCallbacks", "WaitForThreadpoolWorkCallbacks",
		"WaitNamedPipeA", "WaitNamedPipeW",
		"WakeAllConditionVariable", "WakeConditionVariable",
		"WerGetFlags", "WerGetFlagsWorker",
		"WerRegisterAdditionalProcess", "WerRegisterAppLocalDump",
		"WerRegisterCustomMetadata", "WerRegisterExcludedMemoryBlock",
		"WerRegisterFile", "WerRegisterFileWorker",
		"WerRegisterMemoryBlock", "WerRegisterMemoryBlockWorker",
		"WerRegisterRuntimeExceptionModule", "WerRegisterRuntimeExceptionModuleWorker",
		"WerSetFlags", "WerSetFlagsWorker",
		"WerUnregisterAdditionalProcess", "WerUnregisterAppLocalDump",
		"WerUnregisterCustomMetadata", "WerUnregisterExcludedMemoryBlock",
		"WerUnregisterFile", "WerUnregisterFileWorker",
		"WerUnregisterMemoryBlock", "WerUnregisterMemoryBlockWorker",
		"WerUnregisterRuntimeExceptionModule", "WerUnregisterRuntimeExceptionModuleWorker",
		"WerpCleanupMessageMapping", "WerpGetDebugger",
		"WerpInitiateRemoteRecovery", "WerpNotifyLoadStringResource",
		"WerpNotifyLoadStringResourceEx", "WerpNotifyUseStringResource",
		"WerpStringLookup", "WideCharToMultiByte", "WinExec", "Wow64DisableWow64FsRedirection",
		"Wow64EnableWow64FsRedirection", "Wow64GetThreadContext",
		"Wow64GetThreadSelectorEntry", "Wow64RevertWow64FsRedirection",
		"Wow64SetThreadContext", "Wow64SuspendThread", "WriteConsoleA", "WriteConsoleInputA",
		"WriteConsoleInputVDMA", "WriteConsoleInputVDMW",
		"WriteConsoleInputW", "WriteConsoleOutputA",
		"WriteConsoleOutputAttribute", "WriteConsoleOutputCharacterA",
		"WriteConsoleOutputCharacterW", "WriteConsoleOutputW",
		"WriteConsoleW", "WriteFile", "WriteFileEx", "WriteFileGather",
		"WriteFileVlm", "WritePrivateProfileSectionA",
		"WritePrivateProfileSectionW", "WritePrivateProfileStringA",
		"WritePrivateProfileStringW", "WritePrivateProfileStructA",
		"WritePrivateProfileStructW", "WriteProcessMemory",
		"WriteProcessMemoryVlm", "WriteProfileSectionA",
		"WriteProfileSectionW", "WriteProfileStringA",
		"WriteProfileStringW", "WriteTapemark",
		"ZombifyActCtx", "ZombifyActCtxWorker",
		"_hread", "_hwrite", "_lclose", "_lcreat",
		"_llseek", "_lopen", "_lread", "_lwrite",
		"lstrcat", "lstrcatA", "lstrcatW", "lstrcmp",
		"lstrcmpA", "lstrcmpW", "lstrcmpi", "lstrcmpiA",
		"lstrcmpiW", "lstrcpy", "lstrcpyA", "lstrcpyW",
		"lstrcpyn", "lstrcpynA", "lstrcpynW", "lstrlen",
		"lstrlenA", "lstrlenW",
	)

	val msvcrt = arrayOf(
		"_CrtCheckMemory", "_CrtDbgBreak", "_CrtDbgReport", "_CrtDbgReportV",
		"_CrtDbgReportW", "_CrtDbgReportWV", "_CrtDoForAllClientObjects", "_CrtDumpMemoryLeaks",
		"_CrtIsMemoryBlock", "_CrtIsValidHeapPointer", "_CrtIsValidPointer", "_CrtMemCheckpoint",
		"_CrtMemDifference", "_CrtMemDumpAllObjectsSince", "_CrtMemDumpStatistics", "_CrtReportBlockType",
		"_CrtSetAllocHook", "_CrtSetBreakAlloc", "_CrtSetDbgBlockType", "_CrtSetDbgFlag",
		"_CrtSetDumpClient", "_CrtSetReportFile", "_CrtSetReportHook", "_CrtSetReportHook2",
		"_CrtSetReportMode", "_CxxThrowException", "_Getdays", "_Getmonths",
		"_Gettnames", "_HUGE", "_Strftime", "_W_Getdays",
		"_W_Getmonths", "_W_Gettnames", "_Wcsftime", "_XcptFilter",
		"__AdjustPointer", "__C_specific_handler", "__CppXcptFilter", "__CxxFrameHandler",
		"__CxxFrameHandler2", "__CxxFrameHandler3", "__DestructExceptionObject", "__ExceptionPtrAssign",
		"__ExceptionPtrCompare", "__ExceptionPtrCopy", "__ExceptionPtrCopyException", "__ExceptionPtrCreate",
		"__ExceptionPtrCurrentException", "__ExceptionPtrDestroy", "__ExceptionPtrRethrow", "__ExceptionPtrSwap",
		"__ExceptionPtrToBool", "__RTCastToVoid", "__RTDynamicCast", "__RTtypeid",
		"__STRINGTOLD", "___lc_codepage_func", "___lc_collate_cp_func", "___lc_handle_func",
		"___mb_cur_max_func", "___setlc_active_func", "___unguarded_readlc_active_add_func", "__argc",
		"__argv", "__badioinfo", "__crtCompareStringA", "__crtCompareStringW",
		"__crtGetLocaleInfoW", "__crtGetStringTypeW", "__crtLCMapStringA", "__crtLCMapStringW",
		"__daylight", "__dllonexit", "__doserrno", "__dstbias",
		"__fpecode", "__getmainargs", "__initenv", "__iob_func",
		"__isascii", "__iscsym", "__iscsymf", "__lc_codepage",
		"__lc_collate_cp", "__lc_handle", "__lconv_init", "__mb_cur_max",
		"__pctype_func", "__pioinfo", "__pwctype_func", "__pxcptinfoptrs",
		"__set_app_type", "__setlc_active", "__setusermatherr", "__strncnt",
		"__threadhandle", "__threadid", "__toascii", "__unDName",
		"__unDNameEx", "__uncaught_exception", "__unguarded_readlc_active", "__wargv",
		"__wcserror", "__wcserror_s", "__wcsncnt", "__wgetmainargs",
		"__winitenv", "_abs64", "_access", "_access_s",
		"_acmdln", "_aexit_rtn", "_aligned_free", "_aligned_free_dbg",
		"_aligned_malloc", "_aligned_malloc_dbg", "_aligned_offset_malloc", "_aligned_offset_malloc_dbg",
		"_aligned_offset_realloc", "_aligned_offset_realloc_dbg", "_aligned_realloc", "_aligned_realloc_dbg",
		"_amsg_exit", "_assert", "_atodbl", "_atodbl_l",
		"_atof_l", "_atoflt_l", "_atoi64", "_atoi64_l",
		"_atoi_l", "_atol_l", "_atoldbl", "_atoldbl_l",
		"_beep", "_beginthread", "_beginthreadex", "_c_exit",
		"_cabs", "_callnewh", "_calloc_dbg", "_cexit",
		"_cgets", "_cgets_s", "_cgetws", "_cgetws_s",
		"_chdir", "_chdrive", "_chgsign", "_chgsignf",
		"_chmod", "_chsize", "_chsize_s", "_chvalidator",
		"_chvalidator_l", "_clearfp", "_close", "_commit",
		"_commode", "_control87", "_controlfp", "_controlfp_s",
		"_copysign", "_copysignf", "_cprintf", "_cprintf_l",
		"_cprintf_p", "_cprintf_p_l", "_cprintf_s", "_cprintf_s_l",
		"_cputs", "_cputws", "_creat", "_create_locale",
		"_crtAssertBusy", "_crtBreakAlloc", "_crtDbgFlag", "_cscanf",
		"_cscanf_l", "_cscanf_s", "_cscanf_s_l", "_ctime32",
		"_ctime32_s", "_ctime64", "_ctime64_s", "_ctype",
		"_cwait", "_cwprintf", "_cwprintf_l", "_cwprintf_p",
		"_cwprintf_p_l", "_cwprintf_s", "_cwprintf_s_l", "_cwscanf",
		"_cwscanf_l", "_cwscanf_s", "_cwscanf_s_l", "_daylight",
		"_difftime32", "_difftime64", "_dstbias", "_dup",
		"_dup2", "_ecvt", "_ecvt_s", "_endthread",
		"_endthreadex", "_environ", "_eof", "_errno",
		"_execl", "_execle", "_execlp", "_execlpe",
		"_execv", "_execve", "_execvp", "_execvpe",
		"_exit", "_expand", "_expand_dbg", "_fcloseall",
		"_fcvt", "_fcvt_s", "_fdopen", "_fgetchar",
		"_fgetwchar", "_filbuf", "_fileinfo", "_filelength",
		"_filelengthi64", "_fileno", "_findclose", "_findfirst",
		"_findfirst64", "_findfirsti64", "_findnext", "_findnext64",
		"_findnexti64", "_finite", "_finitef", "_flsbuf",
		"_flushall", "_fpclass", "_fpclassf", "_fpreset",
		"_fprintf_l", "_fprintf_p", "_fprintf_p_l", "_fprintf_s_l",
		"_fputchar", "_fputwchar", "_free_dbg", "_free_locale",
		"_freea", "_freea_s", "_fscanf_l", "_fscanf_s_l",
		"_fseeki64", "_fsopen", "_fstat", "_fstat64",
		"_fstati64", "_ftime", "_ftime32", "_ftime32_s",
		"_ftime64", "_ftime64_s", "_fullpath", "_fullpath_dbg",
		"_futime", "_futime32", "_futime64", "_fwprintf_l",
		"_fwprintf_p", "_fwprintf_p_l", "_fwprintf_s_l", "_fwscanf_l",
		"_fwscanf_s_l", "_gcvt", "_gcvt_s", "_get_current_locale",
		"_get_doserrno", "_get_environ", "_get_errno", "_get_fileinfo",
		"_get_fmode", "_get_heap_handle", "_get_osfhandle", "_get_osplatform",
		"_get_osver", "_get_output_format", "_get_pgmptr", "_get_sbh_threshold",
		"_get_wenviron", "_get_winmajor", "_get_winminor", "_get_winver",
		"_get_wpgmptr", "_getch", "_getche", "_getcwd",
		"_getdcwd", "_getdiskfree", "_getdrive", "_getdrives",
		"_getmaxstdio", "_getmbcp", "_getpid", "_getsystime",
		"_getw", "_getwch", "_getwche", "_getws",
		"_gmtime32", "_gmtime32_s", "_gmtime64", "_gmtime64_s",
		"_heapchk", "_heapmin", "_heapset", "_heapwalk",
		"_hypot", "_hypotf", "_i64toa", "_i64toa_s",
		"_i64tow", "_i64tow_s", "_initterm", "_initterm_e",
		"_invalid_parameter", "_iob", "_isalnum_l", "_isalpha_l",
		"_isatty", "_iscntrl_l", "_isctype", "_isctype_l",
		"_isdigit_l", "_isgraph_l", "_isleadbyte_l", "_islower_l",
		"_ismbbalnum", "_ismbbalnum_l", "_ismbbalpha", "_ismbbalpha_l",
		"_ismbbgraph", "_ismbbgraph_l", "_ismbbkalnum", "_ismbbkalnum_l",
		"_ismbbkana", "_ismbbkana_l", "_ismbbkprint", "_ismbbkprint_l",
		"_ismbbkpunct", "_ismbbkpunct_l", "_ismbblead", "_ismbblead_l",
		"_ismbbprint", "_ismbbprint_l", "_ismbbpunct", "_ismbbpunct_l",
		"_ismbbtrail", "_ismbbtrail_l", "_ismbcalnum", "_ismbcalnum_l",
		"_ismbcalpha", "_ismbcalpha_l", "_ismbcdigit", "_ismbcdigit_l",
		"_ismbcgraph", "_ismbcgraph_l", "_ismbchira", "_ismbchira_l",
		"_ismbckata", "_ismbckata_l", "_ismbcl0", "_ismbcl0_l",
		"_ismbcl1", "_ismbcl1_l", "_ismbcl2", "_ismbcl2_l",
		"_ismbclegal", "_ismbclegal_l", "_ismbclower", "_ismbclower_l",
		"_ismbcprint", "_ismbcprint_l", "_ismbcpunct", "_ismbcpunct_l",
		"_ismbcspace", "_ismbcspace_l", "_ismbcsymbol", "_ismbcsymbol_l",
		"_ismbcupper", "_ismbcupper_l", "_ismbslead", "_ismbslead_l",
		"_ismbstrail", "_ismbstrail_l", "_isnan", "_isnanf",
		"_isprint_l", "_isspace_l", "_isupper_l", "_iswalnum_l",
		"_iswalpha_l", "_iswcntrl_l", "_iswctype_l", "_iswdigit_l",
		"_iswgraph_l", "_iswlower_l", "_iswprint_l", "_iswpunct_l",
		"_iswspace_l", "_iswupper_l", "_iswxdigit_l", "_isxdigit_l",
		"_itoa", "_itoa_s", "_itow", "_itow_s",
		"_j0", "_j1", "_jn", "_kbhit",
		"_lfind", "_lfind_s", "_local_unwind", "_localtime32",
		"_localtime32_s", "_localtime64", "_localtime64_s", "_lock",
		"_locking", "_logb", "_logbf", "_lrotl",
		"_lrotr", "_lsearch", "_lsearch_s", "_lseek",
		"_lseeki64", "_ltoa", "_ltoa_s", "_ltow",
		"_ltow_s", "_makepath", "_makepath_s", "_malloc_dbg",
		"_mbbtombc", "_mbbtombc_l", "_mbbtype", "_mbcasemap",
		"_mbccpy", "_mbccpy_l", "_mbccpy_s", "_mbccpy_s_l",
		"_mbcjistojms", "_mbcjistojms_l", "_mbcjmstojis", "_mbcjmstojis_l",
		"_mbclen", "_mbclen_l", "_mbctohira", "_mbctohira_l",
		"_mbctokata", "_mbctokata_l", "_mbctolower", "_mbctolower_l",
		"_mbctombb", "_mbctombb_l", "_mbctoupper", "_mbctoupper_l",
		"_mbctype", "_mblen_l", "_mbsbtype", "_mbsbtype_l",
		"_mbscat", "_mbscat_s", "_mbscat_s_l", "_mbschr",
		"_mbschr_l", "_mbscmp", "_mbscmp_l", "_mbscoll",
		"_mbscoll_l", "_mbscpy", "_mbscpy_s", "_mbscpy_s_l",
		"_mbscspn", "_mbscspn_l", "_mbsdec", "_mbsdec_l",
		"_mbsdup", "_mbsicmp", "_mbsicmp_l", "_mbsicoll",
		"_mbsicoll_l", "_mbsinc", "_mbsinc_l", "_mbslen",
		"_mbslen_l", "_mbslwr", "_mbslwr_l", "_mbslwr_s",
		"_mbslwr_s_l", "_mbsnbcat", "_mbsnbcat_l", "_mbsnbcat_s",
		"_mbsnbcat_s_l", "_mbsnbcmp", "_mbsnbcmp_l", "_mbsnbcnt",
		"_mbsnbcnt_l", "_mbsnbcoll", "_mbsnbcoll_l", "_mbsnbcpy",
		"_mbsnbcpy_l", "_mbsnbcpy_s", "_mbsnbcpy_s_l", "_mbsnbicmp",
		"_mbsnbicmp_l", "_mbsnbicoll", "_mbsnbicoll_l", "_mbsnbset",
		"_mbsnbset_l", "_mbsnbset_s", "_mbsnbset_s_l", "_mbsncat",
		"_mbsncat_l", "_mbsncat_s", "_mbsncat_s_l", "_mbsnccnt",
		"_mbsnccnt_l", "_mbsncmp", "_mbsncmp_l", "_mbsncoll",
		"_mbsncoll_l", "_mbsncpy", "_mbsncpy_l", "_mbsncpy_s",
		"_mbsncpy_s_l", "_mbsnextc", "_mbsnextc_l", "_mbsnicmp",
		"_mbsnicmp_l", "_mbsnicoll", "_mbsnicoll_l", "_mbsninc",
		"_mbsninc_l", "_mbsnlen", "_mbsnlen_l", "_mbsnset",
		"_mbsnset_l", "_mbsnset_s", "_mbsnset_s_l", "_mbspbrk",
		"_mbspbrk_l", "_mbsrchr", "_mbsrchr_l", "_mbsrev",
		"_mbsrev_l", "_mbsset", "_mbsset_l", "_mbsset_s",
		"_mbsset_s_l", "_mbsspn", "_mbsspn_l", "_mbsspnp",
		"_mbsspnp_l", "_mbsstr", "_mbsstr_l", "_mbstok",
		"_mbstok_l", "_mbstok_s", "_mbstok_s_l", "_mbstowcs_l",
		"_mbstowcs_s_l", "_mbstrlen", "_mbstrlen_l", "_mbstrnlen",
		"_mbstrnlen_l", "_mbsupr", "_mbsupr_l", "_mbsupr_s",
		"_mbsupr_s_l", "_mbtowc_l", "_memccpy", "_memicmp",
		"_memicmp_l", "_mkdir", "_mkgmtime", "_mkgmtime32",
		"_mkgmtime64", "_mktemp", "_mktemp_s", "_mktime32",
		"_mktime64", "_msize", "_msize_dbg", "_nextafter",
		"_nextafterf", "_onexit", "_open", "_open_osfhandle",
		"_osplatform", "_osver", "_pclose", "_pctype",
		"_pgmptr", "_pipe", "_popen", "_printf_l",
		"_printf_p", "_printf_p_l", "_printf_s_l", "_purecall",
		"_putch", "_putenv", "_putenv_s", "_putw",
		"_putwch", "_putws", "_pwctype", "_read",
		"_realloc_dbg", "_resetstkoflw", "_rmdir", "_rmtmp",
		"_rotl", "_rotl64", "_rotr", "_rotr64",
		"_scalb", "_scalbf", "_scanf_l", "_scanf_s_l",
		"_scprintf", "_scprintf_l", "_scprintf_p_l", "_scwprintf",
		"_scwprintf_l", "_scwprintf_p_l", "_searchenv", "_searchenv_s",
		"_set_controlfp", "_set_doserrno", "_set_errno", "_set_error_mode",
		"_set_fileinfo", "_set_fmode", "_set_output_format", "_set_sbh_threshold",
		"_seterrormode", "_setjmp", "_setjmpex", "_setmaxstdio",
		"_setmbcp", "_setmode", "_setsystime", "_sleep",
		"_snprintf", "_snprintf_c", "_snprintf_c_l", "_snprintf_l",
		"_snprintf_s", "_snprintf_s_l", "_snscanf", "_snscanf_l",
		"_snscanf_s", "_snscanf_s_l", "_snwprintf", "_snwprintf_l",
		"_snwprintf_s", "_snwprintf_s_l", "_snwscanf", "_snwscanf_l",
		"_snwscanf_s", "_snwscanf_s_l", "_sopen", "_sopen_s",
		"_spawnl", "_spawnle", "_spawnlp", "_spawnlpe",
		"_spawnv", "_spawnve", "_spawnvp", "_spawnvpe",
		"_splitpath", "_splitpath_s", "_sprintf_l", "_sprintf_p_l",
		"_sprintf_s_l", "_sscanf_l", "_sscanf_s_l", "_stat",
		"_stat64", "_stati64", "_statusfp", "_strcmpi",
		"_strcoll_l", "_strdate", "_strdate_s", "_strdup",
		"_strdup_dbg", "_strerror", "_strerror_s", "_stricmp",
		"_stricmp_l", "_stricoll", "_stricoll_l", "_strlwr",
		"_strlwr_l", "_strlwr_s", "_strlwr_s_l", "_strncoll",
		"_strncoll_l", "_strnicmp", "_strnicmp_l", "_strnicoll",
		"_strnicoll_l", "_strnset", "_strnset_s", "_strrev",
		"_strset", "_strset_s", "_strtime", "_strtime_s",
		"_strtod_l", "_strtoi64", "_strtoi64_l", "_strtol_l",
		"_strtoui64", "_strtoui64_l", "_strtoul_l", "_strupr",
		"_strupr_l", "_strupr_s", "_strupr_s_l", "_strxfrm_l",
		"_swab", "_swprintf", "_swprintf_c", "_swprintf_c_l",
		"_swprintf_p_l", "_swprintf_s_l", "_swscanf_l", "_swscanf_s_l",
		"_sys_errlist", "_sys_nerr", "_tell", "_telli64",
		"_tempnam", "_tempnam_dbg", "_time32", "_time64",
		"_timezone", "_tolower", "_tolower_l", "_toupper",
		"_toupper_l", "_towlower_l", "_towupper_l", "_tzname",
		"_tzset", "_ui64toa", "_ui64toa_s", "_ui64tow",
		"_ui64tow_s", "_ultoa", "_ultoa_s", "_ultow",
		"_ultow_s", "_umask", "_umask_s", "_ungetch",
		"_ungetwch", "_unlink", "_unlock", "_utime",
		"_utime32", "_utime64", "_vcprintf", "_vcprintf_l",
		"_vcprintf_p", "_vcprintf_p_l", "_vcprintf_s", "_vcprintf_s_l",
		"_vcwprintf", "_vcwprintf_l", "_vcwprintf_p", "_vcwprintf_p_l",
		"_vcwprintf_s", "_vcwprintf_s_l", "_vfprintf_l", "_vfprintf_p",
		"_vfprintf_p_l", "_vfprintf_s_l", "_vfwprintf_l", "_vfwprintf_p",
		"_vfwprintf_p_l", "_vfwprintf_s_l", "_vprintf_l", "_vprintf_p",
		"_vprintf_p_l", "_vprintf_s_l", "_vscprintf", "_vscprintf_l",
		"_vscprintf_p_l", "_vscwprintf", "_vscwprintf_l", "_vscwprintf_p_l",
		"_vsnprintf", "_vsnprintf_c", "_vsnprintf_c_l", "_vsnprintf_l",
		"_vsnprintf_s", "_vsnprintf_s_l", "_vsnwprintf", "_vsnwprintf_l",
		"_vsnwprintf_s", "_vsnwprintf_s_l", "_vsprintf_l", "_vsprintf_p",
		"_vsprintf_p_l", "_vsprintf_s_l", "_vswprintf", "_vswprintf_c",
		"_vswprintf_c_l", "_vswprintf_l", "_vswprintf_p_l", "_vswprintf_s_l",
		"_vwprintf_l", "_vwprintf_p", "_vwprintf_p_l", "_vwprintf_s_l",
		"_waccess", "_waccess_s", "_wasctime", "_wasctime_s",
		"_wassert", "_wchdir", "_wchmod", "_wcmdln",
		"_wcreat", "_wcscoll_l", "_wcsdup", "_wcsdup_dbg",
		"_wcserror", "_wcserror_s", "_wcsftime_l", "_wcsicmp",
		"_wcsicmp_l", "_wcsicoll", "_wcsicoll_l", "_wcslwr",
		"_wcslwr_l", "_wcslwr_s", "_wcslwr_s_l", "_wcsncoll",
		"_wcsncoll_l", "_wcsnicmp", "_wcsnicmp_l", "_wcsnicoll",
		"_wcsnicoll_l", "_wcsnset", "_wcsnset_s", "_wcsrev",
		"_wcsset", "_wcsset_s", "_wcstod_l", "_wcstoi64",
		"_wcstoi64_l", "_wcstol_l", "_wcstombs_l", "_wcstombs_s_l",
		"_wcstoui64", "_wcstoui64_l", "_wcstoul_l", "_wcsupr",
		"_wcsupr_l", "_wcsupr_s", "_wcsupr_s_l", "_wcsxfrm_l",
		"_wctime", "_wctime32", "_wctime32_s", "_wctime64",
		"_wctime64_s", "_wctomb_l", "_wctomb_s_l", "_wctype",
		"_wenviron", "_wexecl", "_wexecle", "_wexeclp",
		"_wexeclpe", "_wexecv", "_wexecve", "_wexecvp",
		"_wexecvpe", "_wfdopen", "_wfindfirst", "_wfindfirst64",
		"_wfindfirsti64", "_wfindnext", "_wfindnext64", "_wfindnexti64",
		"_wfopen", "_wfopen_s", "_wfreopen", "_wfreopen_s",
		"_wfsopen", "_wfullpath", "_wfullpath_dbg", "_wgetcwd",
		"_wgetdcwd", "_wgetenv", "_wgetenv_s", "_winmajor",
		"_winminor", "_winput_s", "_winver", "_wmakepath",
		"_wmakepath_s", "_wmkdir", "_wmktemp", "_wmktemp_s",
		"_wopen", "_woutput_s", "_wperror", "_wpgmptr",
		"_wpopen", "_wprintf_l", "_wprintf_p", "_wprintf_p_l",
		"_wprintf_s_l", "_wputenv", "_wputenv_s", "_wremove",
		"_wrename", "_write", "_wrmdir", "_wscanf_l",
		"_wscanf_s_l", "_wsearchenv", "_wsearchenv_s", "_wsetlocale",
		"_wsopen", "_wsopen_s", "_wspawnl", "_wspawnle",
		"_wspawnlp", "_wspawnlpe", "_wspawnv", "_wspawnve",
		"_wspawnvp", "_wspawnvpe", "_wsplitpath", "_wsplitpath_s",
		"_wstat", "_wstat64", "_wstati64", "_wstrdate",
		"_wstrdate_s", "_wstrtime", "_wstrtime_s", "_wsystem",
		"_wtempnam", "_wtempnam_dbg", "_wtmpnam", "_wtmpnam_s",
		"_wtof", "_wtof_l", "_wtoi", "_wtoi64",
		"_wtoi64_l", "_wtoi_l", "_wtol", "_wtol_l",
		"_wunlink", "_wutime", "_wutime32", "_wutime64",
		"_y0", "_y1", "_yn", "abort",
		"abs", "acos", "acosf", "asctime",
		"asctime_s", "asin", "asinf", "atan",
		"atan2", "atan2f", "atanf", "atexit",
		"atof", "atoi", "atol", "bsearch",
		"bsearch_s", "btowc", "calloc", "ceil",
		"ceilf", "clearerr", "clearerr_s", "clock",
		"cos", "cosf", "cosh", "coshf",
		"ctime", "difftime", "div", "exit",
		"exp", "expf", "fabs", "fclose",
		"feof", "ferror", "fflush", "fgetc",
		"fgetpos", "fgets", "fgetwc", "fgetws",
		"floor", "floorf", "fmod", "fmodf",
		"fopen", "fopen_s", "fprintf", "fprintf_s",
		"fputc", "fputs", "fputwc", "fputws",
		"fread", "free", "freopen", "freopen_s",
		"frexp", "fscanf", "fscanf_s", "fseek",
		"fsetpos", "ftell", "fwprintf", "fwprintf_s",
		"fwrite", "fwscanf", "fwscanf_s", "getc",
		"getchar", "getenv", "getenv_s", "gets",
		"getwc", "getwchar", "gmtime", "is_wctype",
		"isalnum", "isalpha", "iscntrl", "isdigit",
		"isgraph", "isleadbyte", "islower", "isprint",
		"ispunct", "isspace", "isupper", "iswalnum",
		"iswalpha", "iswascii", "iswcntrl", "iswctype",
		"iswdigit", "iswgraph", "iswlower", "iswprint",
		"iswpunct", "iswspace", "iswupper", "iswxdigit",
		"isxdigit", "labs", "ldexp", "ldiv",
		"localeconv", "localtime", "log", "log10",
		"log10f", "logf", "longjmp", "malloc",
		"mblen", "mbrlen", "mbrtowc", "mbsdup_dbg",
		"mbsrtowcs", "mbsrtowcs_s", "mbstowcs", "mbstowcs_s",
		"mbtowc", "memchr", "memcmp", "memcpy",
		"memcpy_s", "memmove", "memmove_s", "memset",
		"mktime", "modf", "modff", "perror",
		"pow", "powf", "printf", "printf_s",
		"putc", "putchar", "puts", "putwc",
		"putwchar", "qsort", "qsort_s", "raise",
		"rand", "rand_s", "realloc", "remove",
		"rename", "rewind", "scanf", "scanf_s",
		"setbuf", "setjmp", "setlocale", "setvbuf",
		"signal", "sin", "sinf", "sinh",
		"sinhf", "sprintf", "sprintf_s", "sqrt",
		"sqrtf", "srand", "sscanf", "sscanf_s",
		"strcat", "strcat_s", "strchr", "strcmp",
		"strcoll", "strcpy", "strcpy_s", "strcspn",
		"strerror", "strerror_s", "strftime", "strlen",
		"strncat", "strncat_s", "strncmp", "strncpy",
		"strncpy_s", "strnlen", "strpbrk", "strrchr",
		"strspn", "strstr", "strtod", "strtok",
		"strtok_s", "strtol", "strtoul", "strxfrm",
		"swprintf", "swprintf_s", "swscanf", "swscanf_s",
		"system", "tan", "tanf", "tanh",
		"tanhf", "time", "tmpfile", "tmpfile_s",
		"tmpnam", "tmpnam_s", "tolower", "toupper",
		"towlower", "towupper", "ungetc", "ungetwc",
		"utime", "vfprintf", "vfprintf_s", "vfwprintf",
		"vfwprintf_s", "vprintf", "vprintf_s", "vsnprintf",
		"vsprintf", "vsprintf_s", "vswprintf", "vswprintf_s",
		"vwprintf", "vwprintf_s", "wcrtomb", "wcrtomb_s",
		"wcscat", "wcscat_s", "wcschr", "wcscmp",
		"wcscoll", "wcscpy", "wcscpy_s", "wcscspn",
		"wcsftime", "wcslen", "wcsncat", "wcsncat_s",
		"wcsncmp", "wcsncpy", "wcsncpy_s", "wcsnlen",
		"wcspbrk", "wcsrchr", "wcsrtombs", "wcsrtombs_s",
		"wcsspn", "wcsstr", "wcstod", "wcstok",
		"wcstok_s", "wcstol", "wcstombs", "wcstombs_s",
		"wcstoul", "wcsxfrm", "wctob", "wctomb",
		"wctomb_s", "wprintf", "wprintf_s", "wscanf",
		"wscanf_s",
	)

	val user32 = arrayOf(
		"GetPointerFrameArrivalTimes", "ActivateKeyboardLayout", "AddClipboardFormatListener", "AddVisualIdentifier",
		"AdjustWindowRect", "AdjustWindowRectEx", "AdjustWindowRectExForDpi", "AlignRects",
		"AllowForegroundActivation", "AllowSetForegroundWindow", "AnimateWindow", "AnyPopup",
		"AppendMenuA", "AppendMenuW", "AreDpiAwarenessContextsEqual", "ArrangeIconicWindows",
		"AttachThreadInput", "BeginDeferWindowPos", "BeginPaint", "BlockInput",
		"BringWindowToTop", "BroadcastSystemMessage", "BroadcastSystemMessageA", "BroadcastSystemMessageExA",
		"BroadcastSystemMessageExW", "BroadcastSystemMessageW", "BuildReasonArray", "CalcChildScroll",
		"CalcMenuBar", "CalculatePopupWindowPosition", "CallMsgFilter", "CallMsgFilterA",
		"CallMsgFilterW", "CallNextHookEx", "CallWindowProcA", "CallWindowProcW",
		"CancelShutdown", "CascadeChildWindows", "CascadeWindows", "ChangeClipboardChain",
		"ChangeDisplaySettingsA", "ChangeDisplaySettingsExA", "ChangeDisplaySettingsExW", "ChangeDisplaySettingsW",
		"ChangeMenuA", "ChangeMenuW", "ChangeWindowMessageFilter", "DwmGetDxRgn",
		"ChangeWindowMessageFilterEx", "CharLowerA", "CharLowerBuffA", "CharLowerBuffW",
		"CharLowerW", "CharNextA", "CharNextExA", "CharNextW",
		"CharPrevA", "CharPrevExA", "CharPrevW", "CharToOemA",
		"CharToOemBuffA", "CharToOemBuffW", "CharToOemW", "CharUpperA",
		"CharUpperBuffA", "CharUpperBuffW", "CharUpperW", "CheckDesktopByThreadId",
		"CheckBannedOneCoreTransformApi", "CheckDBCSEnabledExt", "CheckDlgButton", "CheckMenuItem",
		"CheckMenuRadioItem", "CheckProcessForClipboardAccess", "CheckProcessSession", "CheckRadioButton",
		"CheckWindowThreadDesktop", "ChildWindowFromPoint", "ChildWindowFromPointEx", "CliImmSetHotKey",
		"ClientThreadSetup", "ClientToScreen", "ClipCursor", "CloseClipboard",
		"CloseDesktop", "CloseGestureInfoHandle", "CloseTouchInputHandle", "CloseWindow",
		"CloseWindowStation", "ConsoleControl", "ControlMagnification", "CopyAcceleratorTableA",
		"CopyAcceleratorTableW", "CopyIcon", "CopyImage", "CopyRect",
		"CountClipboardFormats", "CreateAcceleratorTableA", "CreateAcceleratorTableW", "CreateCaret",
		"CreateCursor", "CreateDCompositionHwndTarget", "CreateDesktopA", "CreateDesktopExA",
		"CreateDesktopExW", "CreateDesktopW", "CreateDialogIndirectParamA", "CreateDialogIndirectParamAorW",
		"CreateDialogIndirectParamW", "CreateDialogParamA", "CreateDialogParamW", "CreateIcon",
		"CreateIconFromResource", "CreateIconFromResourceEx", "CreateIconIndirect", "CreateMDIWindowA",
		"CreateMDIWindowW", "CreateMenu", "CreatePopupMenu", "CreateSyntheticPointerDevice",
		"CreateSystemThreads", "CreateWindowExA", "CreateWindowExW", "CreateWindowInBand",
		"CreateWindowInBandEx", "CreateWindowIndirect", "CreateWindowStationA", "CreateWindowStationW",
		"CsrBroadcastSystemMessageExW", "CtxInitUser32", "DdeAbandonTransaction", "DdeAccessData",
		"DdeAddData", "DdeClientTransaction", "DdeCmpStringHandles", "DdeConnect",
		"DdeConnectList", "DdeCreateDataHandle", "DdeCreateStringHandleA", "DdeCreateStringHandleW",
		"DdeDisconnect", "DdeDisconnectList", "DdeEnableCallback", "DdeFreeDataHandle",
		"DdeFreeStringHandle", "DdeGetData", "DdeGetLastError", "DdeGetQualityOfService",
		"DdeImpersonateClient", "DdeInitializeA", "DdeInitializeW", "DdeKeepStringHandle",
		"DdeNameService", "DdePostAdvise", "DdeQueryConvInfo", "DdeQueryNextServer",
		"DdeQueryStringA", "DdeQueryStringW", "DdeReconnect", "DdeSetQualityOfService",
		"DdeSetUserHandle", "DdeUnaccessData", "DdeUninitialize", "DefDlgProcA",
		"DefDlgProcW", "DefFrameProcA", "DefFrameProcW", "DefMDIChildProcA",
		"DefMDIChildProcW", "DefRawInputProc", "DefWindowProcA", "DefWindowProcW",
		"DeferWindowPos", "DeferWindowPosAndBand", "DeleteMenu", "DeregisterShellHookWindow",
		"DestroyAcceleratorTable", "DestroyCaret", "DestroyCursor", "DestroyDCompositionHwndTarget",
		"DestroyIcon", "DestroyMenu", "DestroyReasons", "DestroySyntheticPointerDevice",
		"DestroyWindow", "DeviceEventWorker", "DialogBoxIndirectParamA", "DialogBoxIndirectParamAorW",
		"DialogBoxIndirectParamW", "DialogBoxParamA", "DialogBoxParamW", "DisableProcessWindowsGhosting",
		"DispatchMessageA", "DispatchMessageW", "DisplayConfigGetDeviceInfo", "DisplayConfigSetDeviceInfo",
		"DisplayExitWindowsWarnings", "DlgDirListA", "DlgDirListComboBoxA", "DlgDirListComboBoxW",
		"DlgDirListW", "DlgDirSelectComboBoxExA", "DlgDirSelectComboBoxExW", "DlgDirSelectExA",
		"DlgDirSelectExW", "DoSoundConnect", "DoSoundDisconnect", "DragDetect",
		"DragObject", "DrawAnimatedRects", "DrawCaption", "DrawCaptionTempA",
		"DrawCaptionTempW", "DrawEdge", "DrawFocusRect", "DrawFrame",
		"DrawFrameControl", "DrawIcon", "DrawIconEx", "DrawMenuBar",
		"DrawMenuBarTemp", "DrawStateA", "DrawStateW", "DrawTextA",
		"DrawTextExA", "DrawTextExW", "DrawTextW", "DwmGetDxSharedSurface",
		"DwmGetRemoteSessionOcclusionEvent", "DwmGetRemoteSessionOcclusionState",
		"DwmKernelShutdown", "DwmKernelStartup",
		"DwmLockScreenUpdates", "DwmStartRedirection", "DwmStopRedirection", "DwmValidateWindow",
		"EditWndProc", "EmptyClipboard", "EnableMenuItem", "EnableMouseInPointer",
		"EnableNonClientDpiScaling", "EnableOneCoreTransformMode", "EnableScrollBar", "EnableSessionForMMCSS",
		"EnableWindow", "EndDeferWindowPos", "EndDeferWindowPosEx", "EndDialog",
		"EndMenu", "EndPaint", "EndTask", "EnterReaderModeHelper",
		"EnumChildWindows", "EnumClipboardFormats", "EnumDesktopWindows", "EnumDesktopsA",
		"EnumDesktopsW", "EnumDisplayDevicesA", "EnumDisplayDevicesW", "EnumDisplayMonitors",
		"EnumDisplaySettingsA", "EnumDisplaySettingsExA", "EnumDisplaySettingsExW", "EnumDisplaySettingsW",
		"EnumPropsA", "EnumPropsExA", "EnumPropsExW", "EnumPropsW",
		"EnumThreadWindows", "EnumWindowStationsA", "EnumWindowStationsW", "EnumWindows",
		"EqualRect", "EvaluateProximityToPolygon", "EvaluateProximityToRect", "ExcludeUpdateRgn",
		"ExitWindowsEx", "FillRect", "FindWindowA", "FindWindowExA",
		"FindWindowExW", "FindWindowW", "FlashWindow", "FlashWindowEx",
		"FrameRect", "FreeDDElParam", "FrostCrashedWindow", "GetActiveWindow",
		"GetAltTabInfo", "GetAltTabInfoA", "GetAltTabInfoW", "GetAncestor",
		"GetAppCompatFlags2", "GetAppCompatFlags", "GetAsyncKeyState", "GetAutoRotationState",
		"GetAwarenessFromDpiAwarenessContext", "GetCIMSSM", "GetCapture", "GetCaretBlinkTime",
		"GetCaretPos", "GetClassInfoA", "GetClassInfoExA", "GetClassInfoExW",
		"GetClassInfoW", "GetClassLongA", "GetClassLongW", "GetClassNameA",
		"GetClassNameW", "GetClassWord", "GetClientRect", "GetClipCursor",
		"GetClipboardAccessToken", "GetClipboardData", "GetClipboardFormatNameA", "GetClipboardFormatNameW",
		"GetClipboardOwner", "GetClipboardSequenceNumber", "GetClipboardViewer", "GetComboBoxInfo",
		"GetCurrentInputMessageSource", "GetCursor", "GetCursorFrameInfo", "GetCursorInfo",
		"GetCursorPos", "GetDC", "GetDCEx", "GetDesktopID",
		"GetDesktopWindow", "GetDialogBaseUnits", "GetDialogControlDpiChangeBehavior", "GetDialogDpiChangeBehavior",
		"GetDisplayAutoRotationPreferences", "GetDisplayConfigBufferSizes", "GetDlgCtrlID", "GetDlgItem",
		"GetDlgItemInt", "GetDlgItemTextA", "GetDlgItemTextW", "GetDoubleClickTime",
		"GetDpiAwarenessContextForProcess", "GetDpiForMonitorInternal", "GetDpiForSystem", "GetDpiForWindow",
		"GetDpiFromDpiAwarenessContext", "GetExtendedPointerDeviceProperty", "GetFocus", "GetForegroundWindow",
		"GetGUIThreadInfo", "GetGestureConfig", "GetGestureExtraArgs", "GetGestureInfo",
		"GetGuiResources", "GetIconInfo", "GetIconInfoExA", "GetIconInfoExW",
		"GetInputDesktop", "GetInputLocaleInfo", "GetInputState", "GetInternalWindowPos",
		"GetKBCodePage", "GetKeyNameTextA", "GetKeyNameTextW", "GetKeyState",
		"GetKeyboardLayout", "GetKeyboardLayoutList", "GetKeyboardLayoutNameA", "GetKeyboardLayoutNameW",
		"GetKeyboardState", "GetKeyboardType", "GetLastActivePopup", "GetLastInputInfo",
		"GetLayeredWindowAttributes", "GetListBoxInfo",
		"GetMagnificationDesktopColorEffect", "GetMagnificationDesktopMagnification",
		"GetMagnificationDesktopSamplingMode", "GetMagnificationLensCtxInformation", "GetMenu", "GetMenuBarInfo",
		"GetMenuCheckMarkDimensions", "GetMenuContextHelpId", "GetMenuDefaultItem", "GetMenuInfo",
		"GetMenuItemCount", "GetMenuItemID", "GetMenuItemInfoA", "GetMenuItemInfoW",
		"GetMenuItemRect", "GetMenuState", "GetMenuStringA", "GetMenuStringW",
		"GetMessageA", "GetMessageExtraInfo", "GetMessagePos", "GetMessageTime",
		"GetMessageW", "GetMonitorInfoA", "GetMonitorInfoW", "GetMouseMovePointsEx",
		"GetNextDlgGroupItem", "GetNextDlgTabItem", "GetOpenClipboardWindow", "GetParent",
		"GetPhysicalCursorPos", "GetPointerCursorId", "GetPointerDevice", "GetPointerDeviceCursors",
		"GetPointerDeviceInputSpace", "GetPointerDeviceOrientation",
		"GetPointerDeviceProperties", "GetPointerDeviceRects",
		"GetPointerDevices", "GetPointerFrameInfo", "GetPointerFrameInfoHistory", "GetPointerFramePenInfo",
		"GetPointerFramePenInfoHistory", "GetPointerFrameTimes",
		"GetPointerFrameTouchInfo", "GetPointerFrameTouchInfoHistory",
		"GetPointerInfo", "GetPointerInfoHistory", "GetPointerInputTransform", "GetPointerPenInfo",
		"GetPointerPenInfoHistory", "GetPointerTouchInfo", "GetPointerTouchInfoHistory", "GetPointerType",
		"GetPriorityClipboardFormat", "GetProcessDefaultLayout",
		"GetProcessDpiAwarenessInternal", "GetProcessWindowStation",
		"GetProgmanWindow", "GetPropA", "GetPropW", "GetQueueStatus",
		"GetRawInputBuffer", "GetRawInputData", "GetRawInputDeviceInfoA", "GetRawInputDeviceInfoW",
		"GetRawInputDeviceList", "GetRawPointerDeviceData",
		"GetReasonTitleFromReasonCode", "GetRegisteredRawInputDevices",
		"GetScrollBarInfo", "GetScrollInfo", "GetScrollPos", "GetScrollRange",
		"GetSendMessageReceiver", "GetShellChangeNotifyWindow", "GetShellWindow", "GetSubMenu",
		"GetSysColor", "GetSysColorBrush", "GetSystemDpiForProcess", "GetSystemMenu",
		"GetSystemMetrics", "GetSystemMetricsForDpi", "GetTabbedTextExtentA", "GetTabbedTextExtentW",
		"GetTaskmanWindow", "GetThreadDesktop", "GetThreadDpiAwarenessContext", "GetThreadDpiHostingBehavior",
		"GetTitleBarInfo", "GetTopLevelWindow", "GetTopWindow", "GetTouchInputInfo",
		"GetUnpredictedMessagePos", "GetUpdateRect", "GetUpdateRgn", "GetUpdatedClipboardFormats",
		"GetUserObjectInformationA", "GetUserObjectInformationW", "GetUserObjectSecurity", "GetWinStationInfo",
		"GetWindow", "GetWindowBand", "GetWindowCompositionAttribute", "GetWindowCompositionInfo",
		"GetWindowContextHelpId", "GetWindowDC", "GetWindowDisplayAffinity", "GetWindowDpiAwarenessContext",
		"GetWindowDpiHostingBehavior", "GetWindowFeedbackSetting", "GetWindowInfo", "GetWindowLongA",
		"GetWindowLongW", "GetWindowMinimizeRect", "GetWindowModuleFileName", "GetWindowModuleFileNameA",
		"GetWindowModuleFileNameW", "GetWindowPlacement", "GetWindowProcessHandle", "GetWindowRect",
		"GetWindowRgn", "GetWindowRgnBox", "GetWindowRgnEx", "GetWindowTextA",
		"GetWindowTextLengthA", "GetWindowTextLengthW", "GetWindowTextW", "GetWindowThreadProcessId",
		"GetWindowWord", "GhostWindowFromHungWindow", "GrayStringA", "GrayStringW",
		"HideCaret", "HiliteMenuItem", "HungWindowFromGhostWindow", "IMPGetIMEA",
		"IMPGetIMEW", "IMPQueryIMEA", "IMPQueryIMEW", "IMPSetIMEA",
		"IMPSetIMEW", "ImpersonateDdeClientWindow", "InSendMessage", "InSendMessageEx",
		"InflateRect", "InheritWindowMonitor", "InitDManipHook", "InitializeGenericHidInjection",
		"InitializeInputDeviceInjection", "InitializeLpkHooks",
		"InitializeWin32EntryTable", "InitializePointerDeviceInjection",
		"InitializePointerDeviceInjectionEx", "InitializeTouchInjection",
		"InjectDeviceInput", "InjectGenericHidInput",
		"InjectKeyboardInput", "InjectMouseInput", "InjectPointerInput", "InjectSyntheticPointerInput",
		"InjectTouchInput", "InputSpaceRegionFromPoint", "InsertMenuA", "InsertMenuItemA",
		"InsertMenuItemW", "InsertMenuW", "InternalGetWindowIcon", "InternalGetWindowText",
		"IntersectRect", "InvalidateRect", "InvalidateRgn", "InvertRect",
		"IsCharAlphaA", "IsCharAlphaNumericA", "IsCharAlphaNumericW", "IsCharAlphaW",
		"IsCharLowerA", "IsCharLowerW", "IsCharUpperA", "IsCharUpperW",
		"IsChild", "IsClipboardFormatAvailable", "IsDialogMessage", "IsDialogMessageA",
		"IsDialogMessageW", "IsDlgButtonChecked", "IsGUIThread", "IsHungAppWindow",
		"IsIconic", "IsImmersiveProcess", "IsInDesktopWindowBand", "IsMenu",
		"IsProcess16Bit", "IsMouseInPointerEnabled", "IsOneCoreTransformMode", "IsProcessDPIAware",
		"IsQueueAttached", "IsRectEmpty", "IsSETEnabled", "IsServerSideWindow",
		"IsThreadDesktopComposited", "IsThreadTSFEventAware", "IsTopLevelWindow", "IsTouchWindow",
		"IsValidDpiAwarenessContext", "IsWinEventHookInstalled", "IsWindow", "IsWindowArranged",
		"IsWindowEnabled", "IsWindowInDestroy", "IsWindowRedirectedForPrint", "IsWindowUnicode",
		"IsWindowVisible", "IsWow64Message", "IsZoomed", "KillSystemTimer",
		"KillTimer", "LoadAcceleratorsA", "LoadAcceleratorsW", "LoadBitmapA",
		"LoadBitmapW", "LoadCursorA", "LoadCursorFromFileA", "LoadCursorFromFileW",
		"LoadCursorW", "LoadIconA", "LoadIconW", "LoadImageA",
		"LoadImageW", "LoadKeyboardLayoutA", "LoadKeyboardLayoutEx", "LoadKeyboardLayoutW",
		"LoadLocalFonts", "LoadMenuA", "LoadMenuIndirectA", "LoadMenuIndirectW",
		"LoadMenuW", "LoadRemoteFonts", "LoadStringA", "LoadStringW",
		"LockSetForegroundWindow", "LockWindowStation", "LockWindowUpdate", "LockWorkStation",
		"LogicalToPhysicalPoint", "LogicalToPhysicalPointForPerMonitorDPI",
		"LookupIconIdFromDirectory", "LookupIconIdFromDirectoryEx",
		"MBToWCSEx", "MBToWCSExt", "MB_GetString", "MITGetCursorUpdateHandle",
		"MITSetForegroundRoutingInfo", "MITSetInputDelegationMode",
		"MITSetLastInputRecipient", "MITSynthesizeTouchInput",
		"MakeThreadTSFEventAware", "MapDialogRect", "MapPointsByVisualIdentifier", "MapVirtualKeyA",
		"MapVirtualKeyExA", "MapVirtualKeyExW", "MapVirtualKeyW", "MapVisualRelativePoints",
		"MapWindowPoints", "MenuItemFromPoint", "MenuWindowProcA", "MenuWindowProcW",
		"MessageBeep", "MessageBoxA", "MessageBoxExA", "MessageBoxExW",
		"MessageBoxIndirectA", "MessageBoxIndirectW", "MessageBoxTimeoutA", "MessageBoxTimeoutW",
		"MessageBoxW", "ModifyMenuA", "ModifyMenuW", "MonitorFromPoint",
		"MonitorFromRect", "MonitorFromWindow", "MoveWindow", "MsgWaitForMultipleObjects",
		"MsgWaitForMultipleObjectsEx", "NotifyOverlayWindow", "NotifyWinEvent", "OemKeyScan",
		"OemToCharA", "OemToCharBuffA", "OemToCharBuffW", "OemToCharW",
		"OffsetRect", "OpenClipboard", "OpenDesktopA", "OpenDesktopW",
		"OpenIcon", "OpenInputDesktop", "OpenThreadDesktop", "OpenWindowStationA",
		"OpenWindowStationW", "PackDDElParam", "PackTouchHitTestingProximityEvaluation", "PaintDesktop",
		"PaintMenuBar", "PaintMonitor", "PeekMessageA", "PeekMessageW",
		"PhysicalToLogicalPoint", "PhysicalToLogicalPointForPerMonitorDPI", "PostMessageA", "PostMessageW",
		"PostQuitMessage", "PostThreadMessageA", "PostThreadMessageW", "PrintWindow",
		"PrivateExtractIconExA", "PrivateExtractIconExW", "PrivateExtractIconsA", "PrivateExtractIconsW",
		"PrivateSetDbgTag", "PrivateSetRipFlags", "PrivateRegisterICSProc", "PtInRect",
		"QueryBSDRWindow", "QueryDisplayConfig", "QuerySendMessage", "QueryUserCounters",
		"RIMAddInputObserver", "RIMAreSiblingDevices",
		"RIMDeviceIoControl", "RIMEnableMonitorMappingForDevice",
		"RIMFreeInputBuffer", "RIMGetDevicePreparsedData",
		"RIMGetDevicePreparsedDataLockfree", "RIMGetDeviceProperties",
		"RIMGetDevicePropertiesLockfree", "RIMGetPhysicalDeviceRect",
		"RIMGetSourceProcessId", "RIMObserveNextInput",
		"RIMOnPnpNotification", "RIMOnTimerNotification",
		"RIMQueryDevicePath", "RIMReadInput",
		"RIMRegisterForInput", "RIMRemoveInputObserver",
		"RIMSetExtendedDeviceProperty", "RIMSetTestModeStatus",
		"RIMUnregisterForInput", "RIMUpdateInputObserverRegistration",
		"RealChildWindowFromPoint", "RealGetWindowClass",
		"RealGetWindowClassA", "RealGetWindowClassW", "ReasonCodeNeedsBugID", "ReasonCodeNeedsComment",
		"RecordShutdownReason", "RedrawWindow", "RegisterBSDRWindow", "RegisterClassA",
		"RegisterClassExA", "RegisterClassExW", "RegisterClassW", "RegisterClipboardFormatA",
		"RegisterClipboardFormatW", "RegisterDManipHook",
		"RegisterDeviceNotificationA", "RegisterDeviceNotificationW",
		"RegisterErrorReportingDialog", "RegisterFrostWindow",
		"RegisterGhostWindow", "RegisterHotKey",
		"RegisterLogonProcess", "RegisterMessagePumpHook",
		"RegisterPointerDeviceNotifications", "RegisterPointerInputTarget",
		"RegisterPointerInputTargetEx", "RegisterPowerSettingNotification",
		"RegisterRawInputDevices", "RegisterServicesProcess",
		"RegisterSessionPort", "RegisterShellHookWindow",
		"RegisterSuspendResumeNotification", "RegisterSystemThread",
		"RegisterTasklist", "RegisterTouchHitTestingWindow", "RegisterTouchWindow", "RegisterUserApiHook",
		"RegisterWindowMessageA", "RegisterWindowMessageW", "ReleaseCapture", "ReleaseDC",
		"ReleaseDwmHitTestWaiters", "RemoveClipboardFormatListener", "RemoveInjectionDevice", "RemoveMenu",
		"RemovePropA", "RemovePropW", "RemoveThreadTSFEventAwareness", "RemoveVisualIdentifier",
		"ReplyMessage", "ResolveDesktopForWOW", "ReuseDDElParam", "ScreenToClient",
		"ScrollChildren", "ScrollDC", "ScrollWindow", "ScrollWindowEx",
		"SendDlgItemMessageA", "SendDlgItemMessageW", "SendIMEMessageExA", "SendIMEMessageExW",
		"SendInput", "SendMessageA", "SendMessageCallbackA", "SendMessageCallbackW",
		"SendMessageTimeoutA", "SendMessageTimeoutW", "SendMessageW", "SendNotifyMessageA",
		"SendNotifyMessageW", "SetActiveWindow", "SetCapture", "SetCaretBlinkTime",
		"SetCaretPos", "SetClassLongA", "SetClassLongW", "SetClassWord",
		"SetClipboardData", "SetClipboardViewer", "SetConsoleReserveKeys", "SetCoalescableTimer",
		"SetCursor", "SetCursorContents", "SetCursorPos", "SetDebugErrorLevel",
		"SetDeskWallpaper", "SetDesktopColorTransform",
		"SetDialogControlDpiChangeBehavior", "SetDialogDpiChangeBehavior",
		"SetDisplayAutoRotationPreferences", "SetDisplayConfig", "SetDlgItemInt", "SetDlgItemTextA",
		"SetDlgItemTextW", "SetDoubleClickTime", "SetFeatureReportResponse", "SetFocus",
		"SetForegroundWindow", "SetFullscreenMagnifierOffsetsDWMUpdated",
		"SetGestureConfig", "SetImmersiveBackgroundWindow",
		"SetInternalWindowPos", "SetKeyboardState", "SetLastErrorEx", "SetLayeredWindowAttributes",
		"SetLogonNotifyWindow", "SetMagnificationDesktopColorEffect",
		"SetMagnificationDesktopMagnification", "SetMagnificationDesktopMagnifierOffsetsDWMUpdated",
		"SetMagnificationDesktopSamplingMode", "SetMagnificationLensCtxInformation",
		"SetMenu", "SetMenuContextHelpId",
		"SetMenuDefaultItem", "SetMenuInfo", "SetMenuItemBitmaps", "SetMenuItemInfoA",
		"SetMenuItemInfoW", "SetMessageExtraInfo", "SetMessageQueue", "SetMirrorRendering",
		"SetParent", "SetPhysicalCursorPos", "SetPointerDeviceInputSpace", "SetProcessDPIAware",
		"SetProcessDefaultLayout", "SetProcessDpiAwarenessContext",
		"SetProcessDpiAwarenessInternal", "SetProcessRestrictionExemption",
		"SetProcessWindowStation", "SetProgmanWindow", "SetPropA", "SetPropW",
		"SetRect", "SetRectEmpty", "SetScrollInfo", "SetScrollPos",
		"SetScrollRange", "SetShellChangeNotifyWindow", "SetShellWindow", "SetShellWindowEx",
		"SetSysColors", "SetSysColorsTemp", "SetSystemCursor", "SetSystemMenu",
		"SetSystemTimer", "SetTaskmanWindow", "SetThreadDesktop", "SetThreadDpiAwarenessContext",
		"SetThreadDpiHostingBehavior", "SetThreadInputBlocked", "SetTimer", "SetUserObjectInformationA",
		"SetUserObjectInformationW", "SetUserObjectSecurity", "SetWinEventHook", "SetWindowBand",
		"SetWindowCompositionAttribute", "SetWindowCompositionTransition",
		"SetWindowContextHelpId", "SetWindowDisplayAffinity",
		"SetWindowFeedbackSetting", "SetWindowLongA", "SetWindowLongW", "SetWindowPlacement",
		"SetWindowPos", "SetWindowRgn", "SetWindowRgnEx", "SetWindowStationUser",
		"SetWindowTextA", "SetWindowTextW", "SetWindowWord", "SetWindowsHookA",
		"SetWindowsHookExA", "SetWindowsHookExAW", "SetWindowsHookExW", "SetWindowsHookW",
		"SfmDxBindSwapChain", "SfmDxGetSwapChainStats",
		"SfmDxOpenSwapChain", "SfmDxQuerySwapChainBindingStatus",
		"SfmDxReleaseSwapChain", "SfmDxReportPendingBindingsToDwm", "" +
			"SfmDxSetSwapChainBindingStatus", "SfmDxSetSwapChainStats",
		"ShowCaret", "ShowCursor", "ShowOwnedPopups", "ShowScrollBar",
		"ShowStartGlass", "ShowSystemCursor", "ShowWindow", "ShowWindowAsync",
		"ShutdownBlockReasonCreate", "ShutdownBlockReasonDestroy",
		"ShutdownBlockReasonQuery", "SignalRedirectionStartComplete",
		"SkipPointerFrameMessages", "SoftModalMessageBox", "SoundSentry", "SubtractRect",
		"SwapMouseButton", "SwitchDesktop", "SwitchDesktopWithFade", "SwitchToThisWindow",
		"SystemParametersInfoA", "SystemParametersInfoForDpi", "SystemParametersInfoW", "TabbedTextOutA",
		"TabbedTextOutW", "TileChildWindows", "TileWindows", "ToAscii",
		"ToAsciiEx", "ToUnicode", "ToUnicodeEx", "TrackMouseEvent",
		"TrackPopupMenu", "TrackPopupMenuEx", "TranslateAccelerator", "TranslateAcceleratorA",
		"TranslateAcceleratorW", "TranslateMDISysAccel", "TranslateMessage", "TranslateMessageEx",
		"UnhookWinEvent", "UnhookWindowsHook", "UnhookWindowsHookEx", "UnionRect",
		"UnloadKeyboardLayout", "UnlockWindowStation", "UnpackDDElParam", "UnregisterClassA",
		"UnregisterClassW", "UnregisterDeviceNotification",
		"UnregisterHotKey", "UnregisterMessagePumpHook",
		"UnregisterPointerInputTarget", "UnregisterPointerInputTargetEx",
		"UnregisterPowerSettingNotification", "UnregisterSessionPort",
		"UnregisterSuspendResumeNotification", "UnregisterTouchWindow",
		"UnregisterUserApiHook", "UpdateDefaultDesktopThumbnail",
		"UpdateLayeredWindow", "UpdateLayeredWindowIndirect",
		"UpdatePerUserSystemParameters", "UpdateWindow",
		"UpdateWindowInputSinkHints", "UpdateWindowTransform",
		"User32InitializeImmEntryTable", "UserClientDllInitialize",
		"UserHandleGrantAccess", "UserLpkPSMTextOut", "UserLpkTabbedTextOut", "UserRealizePalette",
		"UserRegisterWowHandlers", "VRipOutput", "VTagOutput", "ValidateRect",
		"ValidateRgn", "VkKeyScanA", "VkKeyScanExA", "VkKeyScanExW",
		"VkKeyScanW", "WCSToMBEx", "WINNLSEnableIME", "WINNLSGetEnableStatus",
		"WINNLSGetIMEHotkey", "WaitForInputIdle", "WaitForRedirectionStartComplete", "WaitMessage",
		"Win32PoolAllocationStats", "WinHelpA", "WinHelpW", "WindowFromDC",
		"WindowFromPhysicalPoint", "WindowFromPoint", "_UserTestTokenForInteractive", "keybd_event",
		"mouse_event", "wsprintfA", "wsprintfW", "wvsprintfA",
		"wvsprintfW", "DelegateInput", "UndelegateInput", "HandleDelegatedInput",
		"GetProcessUIContextInformation", "IsThreadMessageQueueAttached", "ReportInertia", "SetCoreWindow",
	)


}